;;; nixos.el --- Browse NixOS options and packages -*- lexical-binding: t -*-

;; Copyright (C) 2025-2026  Daniel Nagy

;; This file is free software: you can redistribute it and/or modify
;; it under the terms of the GNU Affero General Public License as
;; published by the Free Software Foundation, either version 3 of the
;; License, or (at your option) any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU Affero General Public License for more details.

;; You should have received a copy of the GNU Affero General Public
;; License along with this file.  If not, see
;; <https://www.gnu.org/licenses/>.

;; Author: Daniel Nagy
;; Version: 0.1.0
;; Keywords: tools, unix
;; Package-Requires: ((emacs "30.1") (nix-mode "0"))

;;; Commentary:

;; This package provides interactive `completing-read' interfaces for
;; browsing NixOS options and Nix packages.
;;
;; Data sources are configurable via `defcustom':
;;
;;   - `nixos-options-json-file'  -- NixOS option descriptions
;;     (generated by the NixOS manual; see default.nix for an example
;;     of how to expose it via `environment.etc').
;;
;;   - `nixos-search-json-file'   -- output of `nix search --json'
;;     (also demonstrated in default.nix).
;;
;; Commands:
;;
;;   M-x nixos-option   -- browse NixOS options
;;   M-x nixos-package  -- browse Nix packages
;;
;; Both commands use the standard completion framework, so they work
;; with icomplete, vertico, fido-mode, etc.  Annotation support is
;; provided out of the box (marginalia is fine too).
;;
;; Deep integration:
;;
;;   - `nixos-browse-mode' (major mode) powers the detail buffer with
;;     bookmark support and a `b' key to open search.nixos.org.
;;
;;   - `thingatpt' integration: in `nix-mode' buffers, point on a
;;     dotted identifier like `services.foo.enable' yields it via
;;     (thing-at-point 'nixos-option).  Call (nixos-thing-at-point-setup)
;;     from `nix-mode-hook' to enable.
;;
;;   - Completion metadata includes `category' for Marginalia users.
;;
;; Usage:
;;
;;   (with-eval-after-load 'nix-mode
;;     (add-hook 'nix-mode-hook #'nixos-thing-at-point-setup))

;;; Code:

(require 'json)
(require 'thingatpt)
(require 'cl-lib)

;; Forward-declare; nix-mode is optional at compile time.
(defvar nix-instantiate-executable)

(defgroup nixos nil
  "Browse NixOS options and packages."
  :group 'tools
  :prefix "nixos-")

(defcustom nixos-options-json-file "/etc/nixos-options.json"
  "Path to the NixOS options JSON file.

This file should contain a flat JSON object where each key is a
dotted option path (e.g. \"services.postgresql.enable\") and each
value is an object with at least a \"description\" field.

NixOS can populate this via `environment.etc'.  When building via
default.nix, the path is substituted with a Nix store path at
build time."
  :type 'file
  :group 'nixos)

(defcustom nixos-search-json-file "/etc/nixos-search.json"
  "Path to the Nix package search JSON file.

This file should contain the output of `nix search --json'.
Keys typically look like \"legacyPackages.x86_64-linux.htop\".

See default.nix for an example of how to generate this in your
NixOS configuration.  When building via default.nix, the path is
substituted with a Nix store path at build time."
  :type 'file
  :group 'nixos)

(defcustom nixos-annotation-width 70
  "Maximum width of the description annotation shown during completion."
  :type 'integer
  :group 'nixos)

(defcustom nixos-option-search-url-template
  "https://search.nixos.org/options?channel=unstable&query=%s"
  "URL template for browsing an option on search.nixos.org.
%s is replaced with the option name."
  :type 'string
  :group 'nixos)

(defcustom nixos-package-search-url-template
  "https://search.nixos.org/packages?channel=unstable&query=%s"
  "URL template for browsing a package on search.nixos.org.
%s is replaced with the package name."
  :type 'string
  :group 'nixos)



;;; Faces

(defface nixos-package-name
  '((t :inherit (package-name bold) :height 1.2))
  "Face for option and package names in nixos detail buffers.
Inherits from `package-name' when available, otherwise `bold'."
  :group 'nixos)

(defface nixos-field-label
  '((t :inherit (package-help-section-name bold)))
  "Face for field labels in nixos detail buffers.
Inherits from `package-help-section-name' when available."
  :group 'nixos)

(defface nixos-description
  '((t :inherit (package-description default)))
  "Face for descriptions in nixos detail buffers.
Inherits from `package-description' when available."
  :group 'nixos)

(defface nixos-version
  '((t :inherit (marginalia-version shadow)))
  "Face for package versions in nixos detail and table buffers.
Inherits from `marginalia-version' when available."
  :group 'nixos)


;;; Cache

(defvar nixos--options-cache nil
  "Cached hash table of NixOS options.
Keys are dotted option paths; values are alists with keys like
description, type, default, etc.")

(defvar nixos--packages-cache nil
  "Cached hash table of Nix packages.
Keys are full attribute paths (e.g.
\"legacyPackages.x86_64-linux.htop\"); values are alists with
keys like pname, version, description, etc.")

(defvar nixos--packages-keys nil
  "Cached list of short package names (prefix stripped).")

(defvar nixos--package-meta-cache nil
  "Hash table memoizing `nixos--package-meta' results.
Keys are package names, values are alists with keys `meta',
`outPath', `version', `buildInputs' and `nativeBuildInputs'.
Memoized because nix store paths are immutable — the metadata
for a given package name never changes.")

(defun nixos--options-load ()
  "Load NixOS options from `nixos-options-json-file' into cache.
Returns the cached hash table."
  (unless nixos--options-cache
    (if (file-readable-p nixos-options-json-file)
        (with-temp-buffer
          (insert-file-contents nixos-options-json-file)
          (goto-char (point-min))
          (setq nixos--options-cache (json-parse-buffer)))
      (setq nixos--options-cache (make-hash-table :test 'equal))))
  nixos--options-cache)

(defun nixos--packages-load ()
  "Load Nix packages from `nixos-search-json-file' into cache.
Returns the cached hash table."
  (unless nixos--packages-cache
    (if (file-readable-p nixos-search-json-file)
        (let ((table (with-temp-buffer
                       (insert-file-contents nixos-search-json-file)
                       (goto-char (point-min))
                       (json-parse-buffer))))
          (setq nixos--packages-cache table
                nixos--packages-keys
                (mapcar (lambda (k)
                          (string-remove-prefix
                           "legacyPackages.x86_64-linux." k))
                        (hash-table-keys table))))
      (setq nixos--packages-cache (make-hash-table :test 'equal)
            nixos--packages-keys nil)))
  nixos--packages-cache)

(defun nixos-refresh-cache ()
  "Discard cached option and package data.
The next `nixos-option' or `nixos-package' invocation will reload
from the JSON files."
  (interactive)
  (setq nixos--options-cache nil
        nixos--packages-cache nil
        nixos--packages-keys nil
        nixos--package-meta-cache nil)
  (message "nixos: cache cleared"))


;;; Helpers

(defun nixos--slurp-description (inner)
  "Extract a one-line description string from INNER (a hash table)."
  (let ((desc (and (hash-table-p inner) (gethash "description" inner)))
        (pname (and (hash-table-p inner) (gethash "pname" inner))))
    (or desc pname "")))

(defun nixos--trim-description (desc)
  "Collapse newlines in DESC and truncate to `nixos-annotation-width' characters."
  (when (and desc (not (string-empty-p desc)))
    (string-limit (string-replace "\n" " " desc)
                  nixos-annotation-width)))

(defun nixos--annotate (description)
  "Return a right-aligned annotation string for DESCRIPTION."
  (when-let* ((trimmed (nixos--trim-description description)))
    (concat (propertize " " 'display '(space :align-to center))
            trimmed)))


;;; Options

(defun nixos--option-annotate (candidate)
  "Completion annotation function for NixOS option CANDIDATE."
  (nixos--annotate
   (nixos--slurp-description
    (gethash candidate (nixos--options-load)))))

(defun nixos--option-collection (string predicate action)
  "Completion collection for NixOS options.
See `completing-read' for the meaning of STRING, PREDICATE and
ACTION."
  (pcase action
    ('metadata
     '(metadata
       (category . nixos-option)
       (annotation-function . nixos--option-annotate)))
    (_
     (complete-with-action action
                           (hash-table-keys (nixos--options-load))
                           string predicate))))


;;; Packages

(defun nixos--package-annotate (candidate)
  "Completion annotation function for Nix package CANDIDATE."
  (let ((full-key (concat "legacyPackages.x86_64-linux." candidate)))
    (nixos--annotate
     (nixos--slurp-description
      (gethash full-key (nixos--packages-load))))))

(defun nixos--package-collection (string predicate action)
  "Completion collection for Nix packages.
See `completing-read' for the meaning of STRING, PREDICATE and
ACTION."
  (pcase action
    ('metadata
     '(metadata
       (category . nixos-package)
       (annotation-function . nixos--package-annotate)))
    (_
     (nixos--packages-load)              ; ensure nixos--packages-keys exists
     (complete-with-action action
                           nixos--packages-keys
                           string predicate))))


;;; Browse Major Mode

(defvar-keymap nixos-browse-mode-map
  :doc "Keymap for `nixos-browse-mode'."
  :parent special-mode-map
  "b" #'nixos-browse-search-url
  "g" #'nixos-browse-refresh
  "r" #'nixos-browse-show-requisites
  "w" #'nixos-browse-copy-store-path)

(define-derived-mode nixos-browse-mode fundamental-mode "NixOS-Browse"
  "Major mode for browsing NixOS option / package details.

\\{nixos-browse-mode-map}"
  :interactive nil
  (setq-local bookmark-make-record-function #'nixos--bookmark-make-record)
  (setq-local revert-buffer-function #'nixos-browse-refresh))

(defvar-local nixos--browse-type nil
  "The type of item in the current browse buffer: `option' or `package'.")

(defvar-local nixos--browse-name nil
  "The name of the option or package in the current browse buffer.")

(defvar-local nixos--browse-out-path nil
  "Store path of the package in the current browse buffer, if any.")

(defvar-local nixos--browse-homepage nil
  "Homepage URL of the package in the current browse buffer, if any.")

(defvar-local nixos--browse-local nil
  "Non-nil if the current browse buffer shows a local package.
Set by `nixos-package-local', used by `nixos-browse-refresh'
to re-evaluate the local default.nix instead of looking up a
nixpkgs package.")

(defvar-local nixos--browse-local-dir nil
  "Full directory path of the local package, if `nixos--browse-local' is non-nil.
Used by `nixos-browse-refresh' to re-evaluate in the correct directory.")

(defvar-local nixos--browse-url nil
  "Non-nil if the current browse buffer shows a URL package.
Set by `nixos-package-url', used by `nixos-browse-refresh'
to re-evaluate the URL instead of looking up a nixpkgs package.")

(defvar-local nixos--browse-url-str nil
  "The URL of the package, if `nixos--browse-url' is non-nil.
Used by `nixos-browse-refresh' to re-fetch the same URL.")

(defun nixos--browse-setup (type name &optional out-path)
  "Configure the current buffer for browsing TYPE (option or package) NAME."
  (setq nixos--browse-type type
        nixos--browse-name name
        nixos--browse-out-path out-path
        nixos--browse-homepage nil
        nixos--browse-local nil
        nixos--browse-local-dir nil
        nixos--browse-url nil
        nixos--browse-url-str nil))

(defun nixos-browse-show-requisites ()
  "Open the store path of the current package in `nix-store-path-mode'.
This shows requisites, references, derivers, etc."
  (interactive)
  (unless (eq nixos--browse-type 'package)
    (user-error "Requisites view only available for packages"))
  (unless nixos--browse-out-path
    (user-error "No store path available for this package"))
  (require 'nix-store nil t)
  (if (fboundp 'nix-store-show-path)
      (nix-store-show-path nixos--browse-out-path)
    (user-error "nix-store-mode not available; install nix-mode")))

(defun nixos-browse-copy-store-path ()
  "Copy the store path of the current package to the kill ring."
  (interactive)
  (unless (eq nixos--browse-type 'package)
    (user-error "Store path only available for packages"))
  (unless nixos--browse-out-path
    (user-error "No store path available for this package"))
  (kill-new nixos--browse-out-path)
  (message "Copied: %s" nixos--browse-out-path))


;;; Display helpers

(defun nixos--value-to-string (value)
  "Convert a parsed JSON VALUE to a human-readable string."
  (cond
   ((eq value :null) nil)
   ((stringp value) value)
   ((numberp value) (number-to-string value))
   ((memq value '(t :json-false))
    (if (eq value t) "true" "false"))
   ((or (hash-table-p value) (vectorp value))
    (json-serialize value))
   (t (prin1-to-string value))))

(defun nixos-browse-search-url ()
  "Open the current option or package on search.nixos.org."
  (interactive)
  (unless nixos--browse-name
    (user-error "No option or package in this buffer"))
  (let ((url (if (eq nixos--browse-type 'option)
                 (format nixos-option-search-url-template
                         nixos--browse-name)
               (format nixos-package-search-url-template
                       nixos--browse-name))))
    (browse-url url)))

(defun nixos-browse-refresh (&rest _ignored)
  "Refresh the current browse buffer.
Optional IGNORED args accommodate `revert-buffer-function' calling
convention."
  (interactive)
  (unless nixos--browse-name
    (user-error "Nothing to refresh"))
  (let ((pt (point)))
    (cl-case nixos--browse-type
      (option (nixos-option nixos--browse-name))
      (package (cond (nixos--browse-url
                      (nixos-package-url nixos--browse-url-str))
                     (nixos--browse-local
                      (let ((default-directory nixos--browse-local-dir))
                        (nixos-package-local)))
                     (t (nixos-package nixos--browse-name))))
      (t (user-error "Unknown browse type %s" nixos--browse-type)))
    (goto-char pt)))

(defun nixos--display-option (name data)
  "Create a formatted detail buffer for NixOS option NAME with DATA."
  (let ((buf (get-buffer-create (format "*nixos-option %s*" name))))
    (with-current-buffer buf
      (let ((inhibit-read-only t))
        (erase-buffer)
        (nixos-browse-mode)
        (nixos--browse-setup 'option name)
        ;; Title
        (insert (propertize name 'face 'nixos-package-name) "\n\n")
        ;; Fields
        (cl-labels ((field (label value)
                      (insert (propertize (format "%-14s" label) 'face 'nixos-field-label))
                      (when (and value (not (string-empty-p value)))
                        (insert value))
                      (insert "\n")))
          (field "Type:" (gethash "type" data))
          (let ((def (nixos--value-to-string (gethash "default" data))))
            (field "Default:" def))
          (let ((desc (gethash "description" data)))
            (when (and desc (not (eq desc :null)))
              (field "Description:" (propertize desc 'face 'nixos-description))))
          (let ((example (nixos--value-to-string (gethash "example" data))))
            (field "Example:" example))
          (let ((decls (gethash "declarations" data)))
            (when (and decls (not (eq decls :null)))
              (field "Declared by:" nil)
              (dolist (d (if (vectorp decls) (append decls nil) decls))
                (insert "  " d "\n")))))
        (goto-char (point-min))
        (read-only-mode 1)
        (set-buffer-modified-p nil)))
    (pop-to-buffer buf)))

(defun nixos--display-package (name info &optional local)
  "Create a formatted detail buffer for Nix package NAME with INFO.
INFO is an alist from `nixos--package-meta' with keys meta, outPath,
version, buildInputs and nativeBuildInputs.

When LOCAL is non-nil, do not `cd' into the store path even if it
exists — the buffer is for a local project, not an installed Nix
package."
  (let ((meta-data (alist-get 'meta info))
        (out-path (alist-get 'outPath info))
        (buf (get-buffer-create (format "*nixos-package %s*" name))))
    (with-current-buffer buf
      (let ((inhibit-read-only t))
        (erase-buffer)
        (nixos-browse-mode)
        (nixos--browse-setup 'package name out-path)
        ;; Title
        (insert (propertize name 'face 'nixos-package-name) "\n\n")
        (cl-labels ((field (label value)
                      (insert (propertize (format "%-14s" label) 'face 'nixos-field-label))
                      (when (and value (not (string-empty-p value)))
                        (insert value))
                      (insert "\n"))
                    (link (label url)
                      (insert (propertize (format "%-14s" label) 'face 'nixos-field-label))
                      (when url
                        (insert (propertize url
                                            'face 'link
                                            'mouse-face 'highlight
                                            'help-echo url)))
                      (insert "\n")))
          (when out-path
            (field "Store path:"
                   (propertize out-path
                               'face (cond ((file-directory-p out-path)
                                            'dired-directory)
                                           ((file-exists-p out-path) nil)
                                           (t 'error))))
            (if (and (not local) (file-directory-p out-path))
                (cd out-path)))
          ;; Meta fields (hash table from parsed JSON)
          (when meta-data
            (let ((desc (gethash "description" meta-data)))
              (when (and desc (not (eq desc :null)))
                (field "Description:" (propertize desc 'face 'nixos-description))))
            (field "Version:" (propertize (or (gethash "version" meta-data)
                                              (alist-get 'version info)
                                              "")
                                          'face 'nixos-version))
            (let ((hp (gethash "homepage" meta-data)))
              (when (and hp (not (eq hp :null)))
                (setq nixos--browse-homepage hp)
                (link "Homepage:" hp)))
            (let ((repo (alist-get 'repository info)))
              (when (and repo (stringp repo) (not (string-empty-p repo)))
                (link "Repository:" repo)))
            (let ((lic (gethash "license" meta-data)))
              (when lic
                (field "License:"
                       (cond ((hash-table-p lic) (gethash "fullName" lic))
                             ((vectorp lic)
                              (mapconcat (lambda (l)
                                           (or (gethash "fullName" l) ""))
                                         lic ", "))
                             ((stringp lic) lic)
                             (t (nixos--value-to-string lic))))))
            (let ((maint (gethash "maintainers" meta-data)))
              (when (and maint (not (eq maint :null)))
                (field "Maintainers:" nil)
                (dolist (m (if (vectorp maint) (append maint nil) maint))
                  (when (hash-table-p m)
                    (insert "  " (or (gethash "name" m) "") "\n")))))))
        ;; Build dependencies
        ;; Compute global max-name across all dep types for alignment.
        (let ((global-max 0))
          (dolist (dep-type '((buildInputs) (nativeBuildInputs)))
            (let ((deps (alist-get (car dep-type) info)))
              (when (and deps (vectorp deps) (> (length deps) 0))
                (dolist (dep (append deps nil))
                  (let ((n (gethash "name" dep)))
                    (when n
                      (setq global-max (max global-max (string-width n)))))))))
          ;; Display with global alignment.
          (dolist (dep-type `((buildInputs . "Build Inputs:")
                              (nativeBuildInputs . "Native Build Inputs:")))
            (let ((deps (alist-get (car dep-type) info)))
              (when (and deps (vectorp deps) (> (length deps) 0))
                (insert "\n" (propertize (cdr dep-type) 'face 'nixos-field-label) "\n")
                (dolist (dep (append deps nil))
                  (insert "  ")
                  (let ((dep-name (gethash "name" dep))
                        (dep-store (gethash "storePath" dep)))
                    (if dep-name
                        (progn
                          (insert-text-button dep-name
                                              'action (lambda (_) (nixos-package dep-name))
                                              'follow-link t
                                              'face 'link
                                              'help-echo (format "Browse package: %s" dep-name))
                          (when dep-store
                            (insert (make-string
                                     (+ (- global-max (string-width dep-name)) 2)
                                     ?\s))
                            (insert (propertize dep-store
                                                'face (cond ((file-directory-p dep-store)
                                                             'dired-directory)
                                                            ((file-exists-p dep-store) nil)
                                                            (t 'error))))))
                      (insert "???")))
                  (insert "\n"))))))
        (goto-char (point-min))
        (read-only-mode 1)
        (set-buffer-modified-p nil)))
    (pop-to-buffer buf)))

(defconst nixos--package-expr-tail
  (concat
   "  depInfo = deps: map (d:"
   "    { name = d.pname or d.name or \"unknown\";"
   "      storePath = d.outPath;"
   "    }) deps;"
   " in [ pkg.meta pkg.outPath pkg.version"
   "     (depInfo (pkg.buildInputs or []))"
   "     (depInfo (pkg.nativeBuildInputs or []))"
   "     (pkg.pname or \"\")"
   "     (pkg.src.meta.homepage or pkg.src.url or \"\") ]"))

(defun nixos--parse-package-result (result)
  "Parse the JSON RESULT vector from nix-instantiate into an alist.
RESULT is the parsed JSON vector:
  [meta outPath version buildInputs nativeBuildInputs pname repository]
Returns a cons cell (ALIST . \"\") on success, or (nil . ERROR-MSG)."
  (if (not (vectorp result))
      (cons nil (format "Unexpected JSON type (expected array): %S" result))
    (let ((meta (and (>= (length result) 1) (aref result 0)))
          (out (and (>= (length result) 2) (aref result 1)))
          (ver (and (>= (length result) 3) (aref result 2)))
          (build (and (>= (length result) 4) (aref result 3)))
          (native (and (>= (length result) 5) (aref result 4)))
          (pname (and (>= (length result) 6) (aref result 5)))
          (repo (and (>= (length result) 7) (aref result 6))))
      (cons (list (cons 'meta (and meta (not (eq meta :null)) meta))
                  (cons 'outPath (and out (not (eq out :null)) out))
                  (cons 'version (and ver (not (eq ver :null)) ver))
                  (cons 'buildInputs (and build (vectorp build) (not (eq build :null)) build))
                  (cons 'nativeBuildInputs (and native (vectorp native) (not (eq native :null)) native))
                  (cons 'pname (and pname (not (eq pname :json-false)) pname))
                  (cons 'repository (and repo (not (eq repo :json-false)) (not (string-empty-p repo)) repo)))
            ""))))

(defun nixos--call-nix-package-expr (expr &rest extra-args)
  "Call nix-instantiate with EXPR and EXTRA-ARGS, return (RESULT . STDERR).
EXTRA-ARGS are passed directly to call-process before \"-E\".

Returns a cons cell (ALIST . STDERR): on success ALIST is the
parsed package alist and STDERR is an empty string.  On failure
ALIST is nil and STDERR contains the error output.  Returns nil
entirely if nix-instantiate is unavailable."
  (when (and (boundp 'nix-instantiate-executable)
             (stringp nix-instantiate-executable))
    (let* ((stderr-file (make-temp-file "nixos-stderr-"))
           (args (append (list nix-instantiate-executable nil (list t stderr-file) nil)
                         extra-args
                         (list "--strict" "--json" "--eval" "-E" expr))))
      (unwind-protect
          (with-temp-buffer
            (let ((exit-code (apply 'call-process args)))
              (if (zerop exit-code)
                  (progn
                    (goto-char (point-min))
                    (nixos--parse-package-result (json-parse-buffer)))
                (cons nil (with-temp-buffer
                            (insert-file-contents stderr-file)
                            (buffer-string))))))
        (delete-file stderr-file)))))

(defun nixos--call-nix-url-expr (url)
  "Call nix-instantiate with a tarball URL, return (RESULT . STDERR).
Downloads the tarball at URL via builtins.fetchTarball, imports
it with pkgs.callPackage, and extracts package metadata.

Uses --impure since the tarball is fetched without a pinned hash.
Returns the same format as `nixos--call-nix-package-expr'."
  (when (and (boundp 'nix-instantiate-executable)
             (stringp nix-instantiate-executable))
    (let* ((stderr-file (make-temp-file "nixos-stderr-"))
           (expr (concat "{url}: let"
                         "  pkgs = import <nixpkgs> {};"
                         "  pkg = pkgs.callPackage"
                         "    (builtins.fetchTarball url) {};"
                         nixos--package-expr-tail))
           (args (list nix-instantiate-executable nil (list t stderr-file) nil
                       "--impure" "--strict" "--json" "--eval" "-E" expr
                       "--argstr" "url" url)))
      (unwind-protect
          (with-temp-buffer
            (let ((exit-code (apply 'call-process args)))
              (if (zerop exit-code)
                  (progn
                    (goto-char (point-min))
                    (nixos--parse-package-result (json-parse-buffer)))
                (cons nil (with-temp-buffer
                            (insert-file-contents stderr-file)
                            (buffer-string))))))
        (delete-file stderr-file)))))

(defun nixos--package-meta (package-name)
  "Fetch metadata, outPath, version and build deps for PACKAGE-NAME.
Returns an alist with keys `meta' (hash table), `outPath' (string),
`version' (string), `buildInputs' (vector of dep attrsets), and
`nativeBuildInputs' (vector of dep attrsets), or nil if
nix-instantiate is not available.

Results are memoized: since Nix store paths are immutable, the
metadata for a given package is stable forever."
  (unless nixos--package-meta-cache
    (setq nixos--package-meta-cache (make-hash-table :test 'equal)))
  (with-memoization (gethash package-name nixos--package-meta-cache)
    (car (nixos--call-nix-package-expr
          (concat "{cand}: let"
                  "  pkgs = import <nixpkgs> {};"
                  "  segments = builtins.filter builtins.isString"
                  "    (builtins.split \"\\\\.\" cand);"
                  "  pkg = builtins.foldl' (s: seg:"
                  "    builtins.getAttr seg s) pkgs segments;"
                  nixos--package-expr-tail)
          "--argstr" "cand" package-name))))


;;; Bookmarks

(defun nixos--bookmark-make-record ()
  "Create a bookmark record for the current browse buffer.
Intended for use as `bookmark-make-record-function'."
  (unless nixos--browse-name
    (user-error "No option or package to bookmark"))
  `(,(format "NixOS %s: %s"
             (if (eq nixos--browse-type 'option) "option" "package")
             nixos--browse-name)
    (type . ,nixos--browse-type)
    (name . ,nixos--browse-name)
    (handler . nixos--bookmark-jump)
    (local . ,nixos--browse-local)
    (local-dir . ,nixos--browse-local-dir)
    (browse-url . ,nixos--browse-url)
    (browse-url-str . ,nixos--browse-url-str)))

;;;###autoload
(defun nixos--bookmark-jump (bookmark)
  "Restore a nixos BOOKMARK.
Called by the bookmark system."
  (let ((type (alist-get 'type bookmark))
        (name (alist-get 'name bookmark))
        (local (alist-get 'local bookmark))
        (local-dir (alist-get 'local-dir bookmark))
        (browse-url (alist-get 'browse-url bookmark))
        (browse-url-str (alist-get 'browse-url-str bookmark)))
    (cl-case type
      (option (nixos-option name))
      (package (cond (browse-url
                      (nixos-package-url browse-url-str))
                     (local
                      (let ((default-directory local-dir))
                        (nixos-package-local)))
                     (t (nixos-package name))))
      (t (user-error "Unknown bookmark type %s" type)))))


;;; Interactive commands

;;;###autoload
(defun nixos-option (&optional option-name)
  "Browse NixOS options, then display the selected one.
When called interactively, prompt with completion.  When
OPTION-NAME is provided non-interactively, display that option
directly."
  (interactive)
  (let ((cand (or option-name
                  (completing-read "nixos-option> "
                                   #'nixos--option-collection))))
    (let ((data (gethash cand (nixos--options-load))))
      (if data
          (nixos--display-option cand data)
        (user-error "Option `%s' not found" cand)))))

;;;###autoload
(defun nixos-package (&optional package-name)
  "Browse Nix packages, then display the selected one.
When called interactively, prompt with completion.  When
PACKAGE-NAME is provided non-interactively, display that package
directly.

Package metadata (including the store path for requisites view)
is obtained from `nix-instantiate' when available; otherwise the
contents of `nixos-search-json-file' are shown."
  (interactive)
  (let ((cand (or package-name
                  (completing-read "nix-pkg> "
                                   #'nixos--package-collection))))
    (let ((info (nixos--package-meta cand)))
      (if info
          (nixos--display-package cand info)
        ;; Fall back to the search JSON data.
        (let* ((full-key (concat "legacyPackages.x86_64-linux." cand))
               (data (gethash full-key (nixos--packages-load))))
          (if data
              (nixos--display-package
               cand
               (list (cons 'meta data)))
            (user-error "Package `%s' not found" cand)))))))

;;;###autoload
(defun nixos-package-local ()
  "Display the Nix package defined by ./default.nix in `default-directory'.
Evaluates with `pkgs.callPackage ./default.nix {}'.

No memoization — intended for local development where
`default.nix' changes between invocations."
  (interactive)
  (let* ((full-dir (expand-file-name default-directory))
         (display-name (abbreviate-file-name full-dir))
         (default-directory full-dir))
    (unless (file-exists-p "default.nix")
      (user-error "No default.nix in %s" display-name))
    (message "Evaluating %sdefault.nix..." display-name)
    (pcase-let ((`(,info . ,stderr)
                 (nixos--call-nix-package-expr
                  (concat "let"
                          "  pkgs = import <nixpkgs> {};"
                          "  pkg = pkgs.callPackage ./default.nix {};"
                          nixos--package-expr-tail))))
      (if info
          (progn
            (let ((pkg-name (or (alist-get 'pname info) display-name)))
              (nixos--display-package pkg-name info t))
            (setq nixos--browse-local t)
            (setq nixos--browse-local-dir full-dir))
        (user-error "%sdefault.nix:\n%s" display-name stderr)))))

;;;###autoload
(defun nixos-package-url (url)
  "Display the Nix package defined by a tarball at URL.
Downloads and evaluates the tarball via
`builtins.fetchTarball' + `pkgs.callPackage'.

No memoization — intended for remote development where the
tarball may change between invocations."
  (interactive "sNix package URL: ")
  (let ((display-name (file-name-base (file-name-sans-extension (url-unhex-string url)))))
    (message "Evaluating %s..." url)
    (pcase-let ((`(,info . ,stderr)
                 (nixos--call-nix-url-expr url)))
      (if info
          (progn
            (let ((pkg-name (or (alist-get 'pname info) display-name)))
              (nixos--display-package pkg-name info t))
            (setq nixos--browse-url t)
            (setq nixos--browse-url-str url))
        (user-error "URL %s:\n%s" url stderr)))))


;;; Thing-At-Point

(defconst nixos--dotted-identifier-re
  (rx (seq bos
           (any "A-Z" "a-z" "_")
           (* (any "A-Z" "a-z" "0-9" "_" "-" "'" "."))
           "."
           (* (any "A-Z" "a-z" "0-9" "_" "-" "'" ".")))
      eos)
  "Regexp matching a dotted NixOS option or package identifier.
Must contain at least one dot and match Nix identifier rules.")

(defun nixos--option-at-point ()
  "Return the NixOS option reference around point, or nil.
Works in `nix-mode' buffers when point is on a dotted
identifier like \"services.postgresql.enable\"."
  (when (derived-mode-p 'nix-mode)
    (let ((bounds (nixos--option-bounds)))
      (when bounds
        (buffer-substring-no-properties (car bounds) (cdr bounds))))))

(defun nixos--option-bounds ()
  "Return the bounds of a NixOS option reference around point."
  (when (derived-mode-p 'nix-mode)
    (let* ((p (point))
           start end)
      (save-excursion
        ;; Scan backward to the start.
        (skip-chars-backward "-A-Za-z0-9_'.")
        (setq start (point))
        ;; Scan forward to the end.
        (goto-char p)
        (skip-chars-forward "-A-Za-z0-9_'.")
        (setq end (point))
        (when (and (> end start)
                   (string-match-p nixos--dotted-identifier-re
                                   (buffer-substring-no-properties start end)))
          (cons start end))))))

(put 'nixos-option 'bounds-of-thing-at-point #'nixos--option-bounds)
(put 'nixos-option 'thing-at-point #'nixos--option-at-point)

;;;###autoload
(defun nixos-thing-at-point-setup ()
  "Enable `thingatpt' integration for `nixos-option' in the current buffer.
Add this to `nix-mode-hook' for automatic setup:

  (add-hook \\='nix-mode-hook #\\='nixos-thing-at-point-setup)"
  (interactive)
  (setq-local thing-at-point-provider-alist
              (cons '(nixos-option . nixos--option-at-point)
                    thing-at-point-provider-alist)))


;;; Tabulated Browse Mode (shared macro)

(cl-defmacro nixos--define-browse-mode (type &key mode-label buffer-name
                                             columns sort-key
                                             extract-fields
                                             visit-fn url-fmt
                                             cache-fn key-fn)
  "Define a tabulated-list browse mode for TYPE (a symbol, e.g. option).
Internal use only."
  (declare (indent 1))
  (let* ((typestr (symbol-name type))
         (mode (intern (format "nixos-browse-%ss-mode" typestr)))
         (mode-map (intern (format "nixos-browse-%ss-mode-map" typestr)))
         (visit (intern (format "nixos-browse-%ss-visit" typestr)))
         (search-url (intern (format "nixos-browse-%ss-search-url" typestr)))
         (refresh (intern (format "nixos-browse-%ss-refresh" typestr)))
         (cmd (intern (format "nixos-browse-%ss" typestr)))
         (entry-fn (intern (format "nixos-browse-%ss--entry" typestr)))
         (entries-fn (intern (format "nixos-browse-%ss--entries" typestr)))
         (current-name-fn (intern (format "nixos-browse-%ss--current-name" typestr))))
    `(progn
       (defvar-keymap ,mode-map
         :doc ,(format "Keymap for `%s'." mode)
         :parent tabulated-list-mode-map
         "RET" #',visit
         "b"   #',search-url
         "g"   #',refresh)

       (define-derived-mode ,mode tabulated-list-mode
         ,mode-label
         ,(format "Major mode for browsing Nix %s in a sortable table.

\\{%s}" typestr mode-map)
         (setq tabulated-list-format ,columns)
         (setq tabulated-list-padding 2)
         (setq tabulated-list-sort-key ',sort-key)
         (tabulated-list-init-header)
         (hl-line-mode 1))

       (defun ,entry-fn (name data)
         ,(format "Return a `tabulated-list' entry for %s NAME with DATA." typestr)
         (list name (vector (propertize name 'face 'nixos-package-name) ,@extract-fields)))

       (defun ,entries-fn (&optional name-list)
         ,(format "Generate `tabulated-list-entries' for %s.
When NAME-LIST is non-nil, only include entries whose names
appear in the list." typestr)
         (let ((items (,cache-fn))
               entries)
           (if (= (hash-table-count items) 0)
               (user-error "No %s loaded (check the JSON file)" ,typestr)
             (maphash
              (lambda (raw-key data)
                (let ((name ,(if key-fn `(funcall ,key-fn raw-key) 'raw-key)))
                  (when (or (null name-list) (member name name-list))
                    (push (,entry-fn name data) entries))))
              items)
             (nreverse entries))))

       (defun ,current-name-fn ()
         ,(format "Return the %s name at point, or signal an error." typestr)
         (or (tabulated-list-get-id)
             (user-error "No %s on this line" ,typestr)))

       (defun ,visit ()
         ,(format "Display details for the %s at point." typestr)
         (interactive)
         (,visit-fn (,current-name-fn)))

       (defun ,search-url ()
         ,(format "Open the current %s on search.nixos.org." typestr)
         (interactive)
         (browse-url (format ,url-fmt (,current-name-fn))))

       (defun ,refresh ()
         ,(format "Refresh the %s table." typestr)
         (interactive)
         (setq tabulated-list-entries (,entries-fn))
         (tabulated-list-print t))

       ;;;###autoload
       (defun ,cmd (&optional name-list)
         ,(format "Display Nix %s in a browseable table.

%s are shown with sortable columns.
\<%s>
\\[%s] on an entry to view full details,
\\[%s] to open on search.nixos.org,
\\[%s] to reload the data.

When NAME-LIST is non-nil (a list of names), only those entries
are displayed.  This is used by Embark export.

Emacs' built-in narrowing (\\[narrow-to-defun] etc.) can be used
to filter the view in-place." typestr typestr mode-map visit search-url refresh)
         (interactive)
         (let ((buf (get-buffer-create ,buffer-name)))
           (with-current-buffer buf
             (,mode)
             (setq tabulated-list-entries
                   (,entries-fn name-list))
             (tabulated-list-print))
           (switch-to-buffer buf))))))

;; Options table

(nixos--define-browse-mode option
  :mode-label "NixOS-Options"
  :buffer-name "*NixOS Options*"
  :columns [("Option" 50 t) ("Type" 20 t) ("Description" 0 nil)]
  :sort-key ("Option" . nil)
  :extract-fields ((or (gethash "type" data) "")
                   (propertize (or (nixos--trim-description
                                    (nixos--slurp-description data)) "")
                               'face 'nixos-description))
  :visit-fn nixos-option
  :url-fmt nixos-option-search-url-template
  :cache-fn nixos--options-load
  :key-fn nil)


;;; Eldoc

(defun nixos-eldoc-function (callback &rest _ignored)
  "Eldoc documentation function for NixOS options at point.
Calls CALLBACK with the option description when point is on a
NixOS option reference in `nix-mode'.  Only returns docs when the
options cache is already populated (does not trigger a load)."
  (when (and (derived-mode-p 'nix-mode)
             nixos--options-cache)
    (when-let* ((opt (nixos--option-at-point))
                (data (gethash opt nixos--options-cache))
                (desc (nixos--slurp-description data)))
      (funcall callback desc))))

;;;###autoload
(defun nixos-eldoc-setup ()
  "Enable eldoc support for NixOS options in the current buffer.
Add this alongside `nixos-thing-at-point-setup' in
`nix-mode-hook' for full integration:

  (add-hook \='nix-mode-hook #\='nixos-thing-at-point-setup)
  (add-hook \='nix-mode-hook #\='nixos-eldoc-setup)"
  (add-hook 'eldoc-documentation-functions
            #'nixos-eldoc-function nil t))


;;; Marginalia annotators

(defun nixos--marginalia-option-annotator (cand)
  "Marginalia annotator for `nixos-option' completion candidates.
Shows the option type and description."
  (when-let* ((data (gethash cand (nixos--options-load)))
              (type (gethash "type" data))
              (desc (nixos--slurp-description data)))
    (concat (propertize (concat "(" type ")")
                        'face 'marginalia-type)
            " " desc)))

(defun nixos--marginalia-package-annotator (cand)
  "Marginalia annotator for `nixos-package' completion candidates.
Shows the package version and description."
  (let* ((full-key (concat "legacyPackages.x86_64-linux." cand))
         (data (gethash full-key (nixos--packages-load)))
         (version (and data (gethash "version" data)))
         (desc (and data (nixos--slurp-description data))))
    (when (or version desc)
      (concat (when version
                (concat (propertize (concat "(" version ")")
                                    'face 'marginalia-version)
                        " "))
              (or desc "")))))

(defvar marginalia-annotator-registry nil)

(with-eval-after-load 'marginalia
  (add-to-list 'marginalia-annotator-registry
               '(nixos-option nixos--marginalia-option-annotator builtin none))
  (add-to-list 'marginalia-annotator-registry
               '(nixos-package nixos--marginalia-package-annotator builtin none)))


;;; Package Browse Mode

(nixos--define-browse-mode package
  :mode-label "NixOS-Packages"
  :buffer-name "*Nix Packages*"
  :columns [("Package" 40 t) ("Version" 15 t) ("Description" 0 nil)]
  :sort-key ("Package" . nil)
  :extract-fields ((propertize (or (gethash "version" data) "")
                               'face 'nixos-version)
                   (propertize (or (nixos--trim-description
                                    (nixos--slurp-description data)) "")
                               'face 'nixos-description))
  :visit-fn nixos-package
  :url-fmt nixos-package-search-url-template
  :cache-fn nixos--packages-load
  :key-fn (lambda (k) (string-remove-prefix "legacyPackages.x86_64-linux." k)))


;;; Embark

(defvar embark-exporters-alist nil)
(defvar embark-keymap-alist nil)
(defvar embark-general-map nil)

(defun nixos--embark-export-option (candidates)
  "Embark export function for NixOS option CANDIDATES."
  (nixos-browse-options candidates))

(defun nixos--embark-export-package (candidates)
  "Embark export function for Nix package CANDIDATES."
  (nixos-browse-packages candidates))

(defun nixos--embark-browse-option-url (cand)
  "Open CAND on search.nixos.org options."
  (browse-url (format nixos-option-search-url-template cand)))

(defun nixos--embark-browse-package-url (cand)
  "Open CAND on search.nixos.org packages."
  (browse-url (format nixos-package-search-url-template cand)))

(defvar-keymap nixos-embark-option-map
  :doc "Embark actions for NixOS option candidates."
  :parent embark-general-map
  "RET" #'nixos-option
  "b"   #'nixos--embark-browse-option-url
  "i"   #'insert)

(defvar-keymap nixos-embark-package-map
  :doc "Embark actions for Nix package candidates."
  :parent embark-general-map
  "RET" #'nixos-package
  "b"   #'nixos--embark-browse-package-url
  "i"   #'insert)

(with-eval-after-load 'embark
  (add-to-list 'embark-exporters-alist
               '(nixos-option . nixos--embark-export-option))
  (add-to-list 'embark-exporters-alist
               '(nixos-package . nixos--embark-export-package))
  (add-to-list 'embark-keymap-alist
               '(nixos-option . nixos-embark-option-map))
  (add-to-list 'embark-keymap-alist
               '(nixos-package . nixos-embark-package-map)))

(provide 'nixos)
;;; nixos.el ends here
