;;; nixos.el --- Browse NixOS options and packages -*- lexical-binding: t -*-

;; Copyright (C) 2026  Daniel Nagy

;; This file is free software: you can redistribute it and/or modify
;; it under the terms of the GNU Affero General Public License as
;; published by the Free Software Foundation, either version 3 of the
;; License, or (at your option) any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU Affero General Public License for more details.

;; You should have received a copy of the GNU Affero General Public
;; License along with this file.  If not, see
;; <https://www.gnu.org/licenses/>.

;; Author: Daniel Nagy
;; Version: 0.1.0
;; Keywords: tools, unix
;; Package-Requires: ((emacs "30.1") (nix-mode "0"))

;;; Commentary:

;; This package provides interactive `completing-read' interfaces for
;; browsing NixOS options and Nix packages.
;;
;; Data sources are configurable via `defcustom':
;;
;;   - `nixos-options-json-file'  -- NixOS option descriptions
;;     (generated by the NixOS manual; see default.nix for an example
;;     of how to expose it via `environment.etc').
;;
;;   - `nixos-search-json-file'   -- output of `nix search --json'
;;     (also demonstrated in default.nix).
;;
;; Commands:
;;
;;   M-x nixos-option   -- browse NixOS options
;;   M-x nixos-package  -- browse Nix packages
;;   M-x nixos-browse-options / nixos-browse-packages -- table views
;;   M-x nixos-package-local / nixos-package-url -- local/remote pkgs
;;
;; Both commands use the standard completion framework, so they work
;; with icomplete, vertico, fido-mode, etc.  Annotation support is
;; provided out of the box.
;;
;; Deep integration:
;;
;;   - `nixos-browse-mode' (major mode) powers the detail buffer with
;;     bookmark support and a `b' key to open search.nixos.org.
;;
;;   - Browse tables: `nixos-browse-options' / `nixos-browse-packages'
;;     display sortable `tabulated-list-mode' tables with refresh
;;     (`g'), bookmark support, and Embark export targets.
;;
;;   - `thingatpt' integration: in `nix-mode' buffers, point on a
;;     dotted identifier like `services.foo.enable' yields it via
;;     (thing-at-point 'nixos-option).  Call (nixos-thing-at-point-setup)
;;     from `nix-mode-hook' to enable.
;;
;;   - Completion metadata includes `category' for Embark actions.
;;
;; Usage:
;;
;;   (with-eval-after-load 'nix-mode
;;     (add-hook 'nix-mode-hook #'nixos-thing-at-point-setup))
;; Org link types (nixos-package:, nixos-option:, ...) are provided
;; by the separate opt-in module ol-nixos.el:
;;
;;   (with-eval-after-load 'org
;;     (require 'ol-nixos))

;;; Code:

(require 'json)
(require 'thingatpt)
(require 'cl-lib)

;; Forward-declare; nix-mode is optional at compile time.
(defvar nix-instantiate-executable)
(defvar nix-executable)

(defgroup nixos nil
  "Browse NixOS options and packages."
  :group 'tools
  :prefix "nixos-"
  :link '(url-link :tag "Repository" "https://github.com/nagy/nixos.el"))

(defcustom nixos-options-json-file "/etc/nixos-options.json"
  "Path to the NixOS options JSON file.

This file should contain a flat JSON object where each key is a
dotted option path (e.g. \"services.postgresql.enable\") and each
value is an object with at least a \"description\" field.

NixOS can populate this via `environment.etc'.  When building via
default.nix, the path is substituted with a Nix store path at
build time."
  :type 'file
  :group 'nixos)

(defcustom nixos-search-json-file "/etc/nixos-search.json"
  "Path to the Nix package search JSON file.

This file should contain the output of `nix search --json'.
Keys typically look like \"legacyPackages.x86_64-linux.htop\".

See default.nix for an example of how to generate this in your
NixOS configuration.  When building via default.nix, the path is
substituted with a Nix store path at build time."
  :type 'file
  :group 'nixos)

(defcustom nixos-annotation-width 70
  "Maximum width of the description annotation shown during completion."
  :type 'integer
  :group 'nixos)

(defcustom nixos-option-search-url-template
  "https://search.nixos.org/options?channel=unstable&query=%s"
  "URL template for browsing an option on search.nixos.org.
%s is replaced with the option name."
  :type 'string
  :group 'nixos)

(defcustom nixos-package-search-url-template
  "https://search.nixos.org/packages?channel=unstable&query=%s"
  "URL template for browsing a package on search.nixos.org.
%s is replaced with the package name."
  :type 'string
  :group 'nixos)



;;; Faces

(defface nixos-package-name
  '((t :inherit (package-name bold) :height 1.2))
  "Face for option and package names in nixos detail buffers.
Inherits from `package-name' when available, otherwise `bold'."
  :group 'nixos)

(defface nixos-field-label
  '((t :inherit (package-help-section-name bold)))
  "Face for field labels in nixos detail buffers.
Inherits from `package-help-section-name' when available."
  :group 'nixos)

(defface nixos-description
  '((t :inherit (package-description default)))
  "Face for descriptions in nixos detail buffers.
Inherits from `package-description' when available."
  :group 'nixos)

(defface nixos-version
  '((t :inherit (shadow)))
  "Face for package versions in nixos detail and table buffers."
  :group 'nixos)


;;; Cache

(defvar nixos--options-cache nil
  "Cached hash table of NixOS options.
Keys are dotted option paths; values are alists with keys like
description, type, default, etc.")

(defvar nixos--packages-cache nil
  "Cached hash table of Nix packages.
Keys are full attribute paths (e.g.
\"legacyPackages.x86_64-linux.htop\"); values are alists with
keys like pname, version, description, etc.")

(defvar nixos--packages-keys nil
  "Cached list of short package names (prefix stripped).")

(defvar nixos--package-key-prefix nil
  "The system attribute prefix of the loaded nix search JSON.
E.g. \"legacyPackages.x86_64-linux.\".  Derived from the first key of
`nixos-search-json-file' in `nixos--packages-load', so the package is
correct on every Nix platform.  Nil until the package data is loaded.")

(defvar nixos--package-meta-cache nil
  "Hash table memoizing `nixos--package-meta' results.
Keys are package names, values are alists with keys `meta',
`outPath', `version', `buildInputs' and `nativeBuildInputs'.
Memoized because nix store paths are immutable — the metadata
for a given package name never changes.")

(defvar nixos--nixpkgs-root nil
  "Cached nixpkgs source root, discovered from NIX_PATH on first use.
Set by `nixos--ensure-nixpkgs-root' via nix-instantiate.
Since store paths are immutable, this cache never expires.")

(defvar nixos--flake-cache nil
  "Cached hash table of flake leaves from `nixos-flake'.
Keys are full dotted output paths (e.g.
\"packages.x86_64-linux.hello\"); values are the leaf hash tables
from `nix flake show --json'.")

(defvar nixos--flake-ref nil
  "The flake reference currently loaded into `nixos--flake-cache'.")

(defun nixos--options-load ()
  "Load NixOS options from `nixos-options-json-file' into cache.
Returns the cached hash table."
  (unless nixos--options-cache
    (if (file-readable-p nixos-options-json-file)
        (with-temp-buffer
          (insert-file-contents nixos-options-json-file)
          (goto-char (point-min))
          (setq nixos--options-cache (json-parse-buffer)))
      (setq nixos--options-cache (make-hash-table :test 'equal))))
  nixos--options-cache)

(defun nixos--packages-load ()
  "Load Nix packages from `nixos-search-json-file' into cache.
Returns the cached hash table."
  (unless nixos--packages-cache
    (if (file-readable-p nixos-search-json-file)
        (let ((table (with-temp-buffer
                       (insert-file-contents nixos-search-json-file)
                       (goto-char (point-min))
                       (json-parse-buffer))))
          (let* ((keys (hash-table-keys table))
                 ;; Derive the system prefix from the first key, so the
                 ;; package is correct on every Nix platform and other
                 ;; systems' keys get stripped rather than leaking.
                 (prefix (if keys
                             (string-match
                              "\\`legacyPackages\\.\\([a-z0-9_-]+\\)\\."
                              (car keys))
                           nil)))
            (setq nixos--package-key-prefix
                  (if prefix
                      (substring (car keys) 0 (match-end 0))
                    ""))
            (setq nixos--packages-cache table
                  nixos--packages-keys
                  (sort (mapcar (lambda (k)
                                  (string-remove-prefix
                                   nixos--package-key-prefix k))
                                keys)
                        #'string<))))
      (setq nixos--packages-cache (make-hash-table :test 'equal)
            nixos--packages-keys nil
            nixos--package-key-prefix "")))
  nixos--packages-cache)

(defun nixos-refresh-cache ()
  "Discard cached option and package data.
The next `nixos-option' or `nixos-package' invocation will reload
from the JSON files.

Clears the options, packages and package-metadata caches.
`nixos--nixpkgs-root' is intentionally NOT cleared: the nixpkgs
store path never changes within a session, so re-discovering it
would be wasted work (see `nixos--ensure-nixpkgs-root')."
  (interactive)
  (setq nixos--options-cache nil
        nixos--packages-cache nil
        nixos--packages-keys nil
        nixos--package-key-prefix nil
        nixos--package-meta-cache nil
        nixos--flake-cache nil
        nixos--flake-ref nil)
  (message "nixos: cache cleared"))

(defun nixos--ensure-nixpkgs-root ()
  "Ensure `nixos--nixpkgs-root' is set from NIX_PATH.
Calls nix-instantiate once to query `builtins.nixPath',
then extracts the first `<nixpkgs>' entry.  Result is cached
permanently since Nix store paths are immutable.

Unlike `nixos-refresh-cache', this cache is deliberately never
cleared: nixpkgs store paths never change within a session, so a
cleared cache would only mean re-running nix-instantiate for the
same value.  When the nixpkgs channel changes (e.g. a NixOS
upgrade), the Emacs session is restarted anyway."
  (unless nixos--nixpkgs-root
    (when (and (boundp 'nix-instantiate-executable)
               (stringp nix-instantiate-executable))
      (condition-case err
          (with-temp-buffer
            (when (zerop (call-process nix-instantiate-executable nil t nil
                                       "--json" "--eval" "--expr"
                                       "builtins.nixPath"))
              (goto-char (point-min))
              (let ((entries (json-parse-buffer)))
                (when (vectorp entries)
                  (catch 'found
                    (dotimes (i (length entries))
                      (let ((entry (aref entries i)))
                        (when (and (hash-table-p entry)
                                   (equal (gethash "prefix" entry) "nixpkgs"))
                          (setq nixos--nixpkgs-root (gethash "path" entry))
                          (throw 'found t)))))))))
        (file-missing (ignore err)))))
  nixos--nixpkgs-root)


;;; Helpers

(defun nixos--slurp-description (inner)
  "Extract a one-line description string from INNER (a hash table)."
  (let ((desc (and (hash-table-p inner) (gethash "description" inner)))
        (pname (and (hash-table-p inner) (gethash "pname" inner))))
    (or desc pname "")))

(defun nixos--trim-description (desc)
  "Collapse newlines in DESC and truncate to `nixos-annotation-width' columns."
  (when (and desc (not (string-empty-p desc)))
    (truncate-string-to-width (string-replace "\n" " " desc)
                              nixos-annotation-width)))

(defun nixos--annotate (description)
  "Return a right-aligned annotation string for DESCRIPTION."
  (when-let* ((trimmed (nixos--trim-description description)))
    (concat (propertize " " 'display '(space :align-to center))
            trimmed)))

(defun nixos--search-names (type term)
  "Return names of TYPE matching TERM as a substring.
TYPE is `option' or `package'.  Matches against the loaded
cache; package names are the short attribute names (system
prefix stripped).  Shared by table bookmarks and the Org
`nixos-*-search:' link types."
  (let ((re (regexp-quote term)))
    (cl-case type
      (option
       (cl-remove-if-not (lambda (name) (string-match-p re name))
                         (hash-table-keys (nixos--options-load))))
      (package
       (nixos--packages-load)
       (cl-remove-if-not (lambda (name) (string-match-p re name))
                         nixos--packages-keys))
      (t (user-error "Unknown type %s" type)))))


;;; Options

(defun nixos--option-annotate (candidate)
  "Completion annotation function for NixOS option CANDIDATE."
  (nixos--annotate
   (nixos--slurp-description
    (gethash candidate (nixos--options-load)))))

(defun nixos--option-collection (string predicate action)
  "Completion collection for NixOS options.
See `completing-read' for the meaning of STRING, PREDICATE and
ACTION."
  (pcase action
    ('metadata
     '(metadata
       (category . nixos-option)
       (annotation-function . nixos--option-annotate)))
    (_
     (complete-with-action action
                           (hash-table-keys (nixos--options-load))
                           string predicate))))


;;; Packages

(defun nixos--package-annotate (candidate)
  "Completion annotation function for Nix package CANDIDATE."
  (let ((full-key (concat nixos--package-key-prefix candidate)))
    (nixos--annotate
     (nixos--slurp-description
      (gethash full-key (nixos--packages-load))))))

(defun nixos--package-collection (string predicate action)
  "Completion collection for Nix packages.
See `completing-read' for the meaning of STRING, PREDICATE and
ACTION."
  (pcase action
    ('metadata
     '(metadata
       (category . nixos-package)
       (annotation-function . nixos--package-annotate)))
    (_
     (nixos--packages-load)              ; ensure nixos--packages-keys exists
     (complete-with-action action
                           nixos--packages-keys
                           string predicate))))


;;; Browse Major Mode

(defvar-keymap nixos-browse-mode-map
  :doc "Keymap for `nixos-browse-mode'."
  :parent special-mode-map
  "b" #'nixos-browse-search-url
  "r" #'nixos-browse-show-requisites
  "w" #'nixos-browse-copy-store-path)

(define-derived-mode nixos-browse-mode special-mode "NixOS-Browse"
  "Major mode for browsing NixOS option / package details.

\\{nixos-browse-mode-map}"
  :interactive nil
  (setq-local bookmark-make-record-function #'nixos--bookmark-make-record)
  (setq-local revert-buffer-function #'nixos-browse-refresh))

(defvar-local nixos--browse-type nil
  "The type of item in the current browse buffer: `option' or `package'.")

(defvar-local nixos--browse-name nil
  "The name of the option or package in the current browse buffer.")

(defvar-local nixos--browse-out-path nil
  "Store path of the package in the current browse buffer, if any.")

(defvar-local nixos--browse-source nil
  "Where the package in the current browse buffer came from.
nil for a nixpkgs package (or an option); (local . DIR) for a
package evaluated from DIR/default.nix; (url . URL) for a
package evaluated from a tarball at URL.  Used by
`nixos-browse-refresh' and bookmarks to re-evaluate the same
source.")

(defvar-local nixos--browse-flake-ref nil
  "The flake reference for the node in the current browse buffer.
Used by `nixos-browse-refresh' and bookmarks to re-run\n`nix flake show' for the same flake.")

(defvar-local nixos--browse-position nil
  "Source position (`meta.position') of the package in the current
browse buffer, if any.  A string of the form
\"/nix/store/.../package.nix:LINE\".")

(defun nixos--browse-setup (type name &optional out-path source position)
  "Configure the current buffer for browsing TYPE (option or package) NAME.
OUT-PATH is the package store path, if any.  SOURCE is the
package origin as understood by `nixos--browse-source'.
POSITION is the package's `meta.position' string, if any."
  (setq nixos--browse-type type
        nixos--browse-name name
        nixos--browse-out-path out-path
        nixos--browse-source source
        nixos--browse-position position))

(defun nixos-browse-show-requisites ()
  "Open the store path of the current package in `nix-store-path-mode'.
This shows requisites, references, derivers, etc."
  (interactive)
  (unless (eq nixos--browse-type 'package)
    (user-error "Requisites view only available for packages"))
  (unless nixos--browse-out-path
    (user-error "No store path available for this package"))
  (require 'nix-store nil t)
  (if (fboundp 'nix-store-show-path)
      (nix-store-show-path nixos--browse-out-path)
    (user-error "nix-store-mode not available; install nix-mode")))

(defun nixos-browse-copy-store-path ()
  "Copy the store path of the current package to the kill ring."
  (interactive)
  (unless (eq nixos--browse-type 'package)
    (user-error "Store path only available for packages"))
  (unless nixos--browse-out-path
    (user-error "No store path available for this package"))
  (kill-new nixos--browse-out-path)
  (message "Copied: %s" nixos--browse-out-path))


;;; Display helpers

(defun nixos--value-to-string (value)
  "Convert a parsed JSON VALUE to a human-readable string."
  (cond
   ((eq value :null) nil)
   ((stringp value) value)
   ((numberp value) (number-to-string value))
   ((memq value '(t :json-false))
    (if (eq value t) "true" "false"))
   ((or (hash-table-p value) (vectorp value))
    (json-serialize value))
   (t (prin1-to-string value))))

(defun nixos-browse-search-url ()
  "Open the current option or package on search.nixos.org."
  (interactive)
  (when (eq nixos--browse-type 'flake)
    (user-error "search.nixos.org does not index flake nodes"))
  (unless nixos--browse-name
    (user-error "No option or package in this buffer"))
  (let ((url (if (eq nixos--browse-type 'option)
                 (format nixos-option-search-url-template
                         nixos--browse-name)
               (format nixos-package-search-url-template
                       nixos--browse-name))))
    (browse-url url)))

(defun nixos-browse-refresh (&rest _ignored)
  "Refresh the current browse buffer.
Optional IGNORED args accommodate `revert-buffer-function' calling
convention."
  (interactive)
  (unless nixos--browse-name
    (user-error "Nothing to refresh"))
  (let ((pt (point)))
    (cl-case nixos--browse-type
      (option (nixos-option nixos--browse-name))
      (package (pcase nixos--browse-source
                 (`(url . ,url) (nixos-package-url url))
                 (`(local . ,dir)
                  (let ((default-directory dir))
                    (nixos-package-local)))
                 (_ (nixos-package nixos--browse-name))))
      (flake (let ((data (and nixos--flake-cache
                              (gethash nixos--browse-name nixos--flake-cache))))
               (if data
                   (nixos--display-flake
                    nixos--browse-name data nixos--browse-flake-ref)
                 (user-error "Flake node `%s' no longer cached"
                             nixos--browse-name))))
      (t (user-error "Unknown browse type %s" nixos--browse-type)))
    (goto-char pt)))

(defun nixos--field (label value &optional face)
  "Insert a LABEL field with VALUE into the current buffer.
LABEL is right-padded to 14 columns.  VALUE may be nil (inserted
as an empty value) or a string; optional FACE is applied to it."
  (insert (propertize (format "%-14s" label) 'face 'nixos-field-label))
  (when (and value (not (string-empty-p value)))
    (insert (if face (propertize value 'face face) value)))
  (insert "\n"))

(defun nixos--link (label url)
  "Insert a clickable LABEL field for URL into the current buffer."
  (insert (propertize (format "%-14s" label) 'face 'nixos-field-label))
  (when url
    (insert-text-button url
                        'action (lambda (_) (browse-url url))
                        'follow-link t
                        'help-echo (format "Browse %s" url)))
  (insert "\n"))

(defun nixos--display-option (name data)
  "Create a formatted detail buffer for NixOS option NAME with DATA."
  (let ((buf (get-buffer-create (format "*nixos-option %s*" name))))
    (with-current-buffer buf
      (let ((inhibit-read-only t))
        (erase-buffer)
        (nixos-browse-mode)
        (nixos--browse-setup 'option name)
        ;; Title
        (insert (propertize name 'face 'nixos-package-name) "\n\n")
        ;; Fields
        (nixos--field "Type:" (gethash "type" data))
        (nixos--field "Default:"
                      (nixos--value-to-string (gethash "default" data)))
        (let ((desc (gethash "description" data)))
          (when (and desc (not (eq desc :null)))
            (nixos--field "Description:" desc 'nixos-description)))
        (nixos--field "Example:"
                      (nixos--value-to-string (gethash "example" data)))
        (let ((decls (gethash "declarations" data)))
          (when (and decls (not (eq decls :null)))
            (nixos--field "Declared by:" nil)
            (dolist (d (if (vectorp decls) (append decls nil) decls))
              (insert "  " d "\n"))))
        ;; Point default-directory at the nixpkgs root so
        ;; embark-dwim / find-file-at-point can resolve relative
        ;; declaration paths like "nixos/modules/programs/htop.nix".
        (when-let* ((decls (gethash "declarations" data))
                    ((vectorp decls))
                    ((> (length decls) 0))
                    (first (aref decls 0))
                    (root (nixos--ensure-nixpkgs-root))
                    (full (expand-file-name first root))
                    ((file-exists-p full)))
          (setq default-directory root))
        (goto-char (point-min))
        (set-buffer-modified-p nil)))
    (pop-to-buffer buf)))

(defun nixos--display-package (name info &optional source)
  "Create a formatted detail buffer for Nix package NAME with INFO.
INFO is an alist from `nixos--package-meta' with keys `meta'
(hash table of package metadata), `outPath' (string store path),
`version' (string), `buildInputs' and `nativeBuildInputs' (vectors
of dep attrsets with `name' and `storePath' keys), `pname'
(string) and `repository' (URL string).

SOURCE is the package origin as understood by
`nixos--browse-source': nil for a nixpkgs package, (local . DIR)
or (url . URL) otherwise.  When SOURCE is non-nil,
`default-directory' is not pointed at the store path — the
buffer is for a local project or a remote tarball, not an
installed Nix package."
  (let ((meta-data (alist-get 'meta info))
        (out-path (alist-get 'outPath info))
        (buf (get-buffer-create (format "*nixos-package %s*" name))))
    (with-current-buffer buf
      (let ((inhibit-read-only t))
        (erase-buffer)
        (nixos-browse-mode)
        (nixos--browse-setup 'package name out-path source (alist-get 'position info))
        ;; Title
        (insert (propertize (format "%-14s" "Name:") 'face 'nixos-field-label)
                (propertize name 'face 'nixos-package-name) "\n")
        (when out-path
          (nixos--field "Store path:"
                        (propertize out-path
                                    'face (cond ((file-directory-p out-path)
                                                 'dired-directory)
                                                ((file-exists-p out-path) nil)
                                                (t 'error))))
          (when (and (null source) (file-directory-p out-path))
            (setq default-directory (file-name-as-directory out-path))))
        ;; Meta fields (hash table from parsed JSON)
        (when meta-data
          (let ((desc (gethash "description" meta-data)))
            (when (and desc (not (eq desc :null)))
              (nixos--field "Description:" desc 'nixos-description)))
          (nixos--field "Version:"
                        (or (gethash "version" meta-data)
                            (alist-get 'version info)
                            "")
                        'nixos-version)
          (let ((hp (gethash "homepage" meta-data)))
            (when (and hp (not (eq hp :null)))
              (nixos--link "Homepage:" hp)))
          (let ((repo (alist-get 'repository info)))
            (when (and repo (stringp repo) (not (string-empty-p repo)))
              (nixos--link "Repository:" repo)))
          (let ((pos (alist-get 'position info)))
            (when (and pos (stringp pos) (not (string-empty-p pos)))
              (nixos--field "Position:" nil)
              (insert-text-button pos
                                  'action (lambda (_) (find-file-at-point pos))
                                  'follow-link t
                                  'help-echo (format "Visit source: %s" pos))
              (insert "\n")))
          (let ((lic (gethash "license" meta-data)))
            (when lic
              (nixos--field "License:"
                            (cond ((hash-table-p lic) (gethash "fullName" lic))
                                  ((vectorp lic)
                                   (mapconcat (lambda (l)
                                                (or (gethash "fullName" l) ""))
                                              lic ", "))
                                  ((stringp lic) lic)
                                  (t (nixos--value-to-string lic))))))
          (let ((maint (gethash "maintainers" meta-data)))
            (when (and maint (not (eq maint :null)))
              (nixos--field "Maintainers:" nil)
              (dolist (m (if (vectorp maint) (append maint nil) maint))
                (when (hash-table-p m)
                  (insert "  " (or (gethash "name" m) "") "\n"))))))
        ;; Build dependencies
        ;; Compute global max-name across all dep types for alignment.
        (let ((global-max 0))
          (dolist (dep-type '((buildInputs) (nativeBuildInputs)))
            (let ((deps (alist-get (car dep-type) info)))
              (when (and deps (vectorp deps) (> (length deps) 0))
                (dolist (dep (append deps nil))
                  (let ((n (gethash "name" dep)))
                    (when n
                      (setq global-max (max global-max (string-width n)))))))))
          ;; Display with global alignment.
          (dolist (dep-type `((buildInputs . "Build Inputs:")
                              (nativeBuildInputs . "Native Build Inputs:")))
            (let ((deps (alist-get (car dep-type) info)))
              (when (and deps (vectorp deps) (> (length deps) 0))
                (insert "\n" (propertize (cdr dep-type) 'face 'nixos-field-label) "\n")
                (dolist (dep (append deps nil))
                  (let ((dep-name (gethash "name" dep))
                        (dep-store (gethash "storePath" dep)))
                    (if dep-name
                        (progn
                          (insert-text-button dep-name
                                              'action (lambda (_) (nixos-package dep-name))
                                              'follow-link t
                                              'face 'link
                                              'help-echo (format "Browse package: %s" dep-name))
                          (when dep-store
                            (insert (make-string
                                     (+ (- global-max (string-width dep-name)) 2)
                                     ?\s))
                            (insert (propertize dep-store
                                                'face (cond ((file-directory-p dep-store)
                                                             'dired-directory)
                                                            ((file-exists-p dep-store) nil)
                                                            (t 'error))))))
                      (insert "???")))
                  (insert "\n"))))))
        (goto-char (point-min))
        (set-buffer-modified-p nil)))
    (pop-to-buffer buf)))


;;; Flakes

(defun nixos--display-flake (name data &optional ref)
  "Create a formatted detail buffer for flake node NAME with DATA.
DATA is the leaf hash table from `nix flake show --json'.  REF is
the flake reference the leaf came from, if known.

Only the data that `flake show --json' emits is shown: the node
type, full path, the derivation name and a description.  There is
no store path, so the requisites view and copy-store-path actions
are unavailable here."
  (let ((buf (get-buffer-create (format "*nixos-flake %s*" name))))
    (with-current-buffer buf
      (let ((inhibit-read-only t))
        (erase-buffer)
        (nixos-browse-mode)
        (nixos--browse-setup 'flake name)
        (setq-local nixos--browse-flake-ref ref)
        ;; Title
        (insert (propertize name 'face 'nixos-package-name) "\n\n")
        ;; Fields
        (let ((type (gethash "type" data)))
          (when type
            (nixos--field "Type:" type)))
        (nixos--field "Path:" name)
        (let ((node-name (gethash "name" data)))
          (when (and node-name (not (eq node-name :null)))
            (nixos--field "Name:" node-name)))
        (let ((desc (gethash "description" data)))
          (when (and desc (not (eq desc :null)) (not (string-empty-p desc)))
            (nixos--field "Description:" desc 'nixos-description)))
        (when ref
          (nixos--field "Flake:" (nixos--abbreviate-path ref)))
        (goto-char (point-min))
        (set-buffer-modified-p nil)))
    (pop-to-buffer buf)))

(defun nixos--flake-leaf-p (node)
  "Return non-nil if NODE is a flake show leaf.
A leaf is a hash table carrying a \"type\" key; intermediate
grouping attrsets and empty system subtrees do not."
  (and (hash-table-p node) (gethash "type" node)))

(defun nixos--flake-flatten (json)
  "Flatten `nix flake show --json' JSON into a path-keyed hash table.
JSON is the parsed top-level hash table.  Returns a hash table
mapping full dotted paths (e.g. \"packages.x86_64-linux.hello\")
to the leaf hash table.

Recurses through every attrset: top-level output attrs, the
optional system level, and any deeper grouping.  A node is a leaf
iff it carries a \"type\" key; nodes without one are descended
into rather than shown."
  (let ((table (make-hash-table :test 'equal)))
    (cl-labels ((walk (path node)
                  (cond
                   ((vectorp node)
                    (dotimes (i (length node))
                      (walk path (aref node i))))
                   ((hash-table-p node)
                    (if (nixos--flake-leaf-p node)
                        (puthash path node table)
                      (maphash
                       (lambda (key child)
                         (let ((seg (if (stringp key) key (prin1-to-string key))))
                           (walk (if (string-empty-p path)
                                     seg
                                   (concat path "." seg))
                                 child)))
                       node))))))
      (walk "" json))
    table))

(defun nixos--call-flake-show (ref)
  "Run `nix flake show --json' for REF, return (JSON . ERROR).
JSON is the parsed hash table on success; ERROR is the stderr on
failure.  Returns nil entirely if the `nix' executable is missing.
REF is passed through `expand-file-name' so a leading `~' resolves
before `nix' sees it (Nix does not expand `~' in flake refs)."
  (let ((ref (if (string-prefix-p "~" ref) (expand-file-name ref) ref))
        (nix-exe (if (and (boundp 'nix-executable)
                          (stringp nix-executable))
                     nix-executable
                   "nix")))
    (condition-case err
        (let* ((stderr-file (make-temp-file "nixos-flake-stderr-"))
               (args (list nix-exe nil (list t stderr-file) nil
                           "--extra-experimental-features"
                           "nix-command flakes"
                           "flake" "show" "--json" ref)))
          (unwind-protect
              (with-temp-buffer
                (let ((exit-code (apply 'call-process args)))
                  (if (zerop exit-code)
                      (cons (progn
                              (goto-char (point-min))
                              (json-parse-buffer))
                            "")
                    (cons nil (with-temp-buffer
                                (insert-file-contents stderr-file)
                                (buffer-string))))))
            (delete-file stderr-file)))
      (file-missing (ignore err) nil))))

(defun nixos--call-flake-metadata (ref)
  "Run `nix flake metadata --json' for REF, return (DATA . ERROR).

DATA is the parsed hash table on success; ERROR is the stderr on
failure.  Returns nil entirely if the `nix' executable is missing.
Unlike `nixos--call-flake-show', this needs no evaluation and
provides flake-level fields (description, path, url, revision,
lastModified, inputs)."
  (let ((ref (if (string-prefix-p "~" ref) (expand-file-name ref) ref))
        (nix-exe (if (and (boundp 'nix-executable)
                          (stringp nix-executable))
                     nix-executable
                   "nix")))
    (condition-case err
        (let* ((stderr-file (make-temp-file "nixos-flake-metadata-stderr-"))
               (args (list nix-exe nil (list t stderr-file) nil
                           "--extra-experimental-features"
                           "nix-command flakes"
                           "flake" "metadata" "--json" ref)))
          (unwind-protect
              (with-temp-buffer
                (let ((exit-code (apply 'call-process args)))
                  (if (zerop exit-code)
                      (cons (progn
                              (goto-char (point-min))
                              (json-parse-buffer))
                            "")
                    (cons nil (with-temp-buffer
                                (insert-file-contents stderr-file)
                                (buffer-string))))))
            (delete-file stderr-file)))
      (file-missing (ignore err) nil))))

(defvar-keymap nixos-flake-overview-mode-map
  :doc "Keymap for `nixos--display-flake-overview' buffers."
  :parent nixos-browse-mode-map
  "RET" #'nixos-flake-visit-output)

(defun nixos-flake-visit-output ()
  "Display details for the flake output at point.

Intended for `nixos--display-flake-overview' buffers, where each
output line is an \`insert-text-button' carrying its node path as
\='button-data'.  Opens that node's detail buffer."
  (interactive)
  (let ((btn (button-at (point))))
    (if btn
        (let ((name (button-get btn 'button-data)))
          (nixos--display-flake name (gethash name nixos--flake-cache)
                                nixos--flake-ref))
      (user-error "No flake output on this line"))))

(defun nixos--flake-input-source (node)
  "Return a display string for an input NODE: source (and date), or nil.

The source is formatted from the node's \"locked\"/\"original\"
attrsets.  For github inputs this is \"github:OWNER/REPO/REV\"; for
local path/file inputs the URL is abbreviated.  When a lastModified
timestamp is present, the date is appended in parens, matching the
official `nix flake metadata' input tree."
  (when (hash-table-p node)
    (let* ((locked (gethash "locked" node))
           (orig (gethash "original" node))
           (type (or (and (hash-table-p locked) (gethash "type" locked))
                     (and (hash-table-p orig) (gethash "type" orig))))
           (owner (and (hash-table-p locked) (gethash "owner" locked)))
           (repo (and (hash-table-p locked) (gethash "repo" locked)))
           (rev (and (hash-table-p locked) (gethash "rev" locked)))
           (url (or (and (hash-table-p locked) (gethash "url" locked))
                    (and (hash-table-p orig) (gethash "url" locked))))
           (last (and (hash-table-p locked) (gethash "lastModified" locked)))
           (src (cond
                 ((and (equal type "github") owner repo rev)
                  (format "github:%s/%s/%s" owner repo rev))
                 ((stringp url)
                  ;; Local file/path inputs: strip a file:// prefix and
                  ;; abbreviate the resulting filesystem path (~).
                  (if (string-prefix-p "file://" url)
                      (abbreviate-file-name
                       (url-unhex-string (substring url 7)))
                    url))
                 (t nil))))
      (when src
        (if (and last (not (eq last :null)))
            (format "%s (%s)" src
                    (format-time-string "%Y-%m-%d %H:%M:%S"
                                        (seconds-to-time last)))
          src)))))

(defun nixos--flake-input-tree (nodes root)
  "Return the input tree display lines for NODES rooted at ROOT.

NODES is the \"locks.nodes\" hash table and ROOT the node id of the
flake itself.  Walks each node's \"inputs\", rendering a nested tree
matching the official `nix flake metadata' output: a non-last sibling
uses \"├───\", the last uses \"└───\", children are indented under
their parent with \"│   \"/\"    \".  An input whose value is a vector
follows another input and renders as NAME follows input X; a
string value names the child node to recurse into."
  (let (lines)
    (cl-labels ((walk (node-id prefix visited)
                  (let* ((node (gethash node-id nodes))
                         (inputs (and (hash-table-p node)
                                      (gethash "inputs" node)))
                         (names (and inputs
                                     (sort (let (acc)
                                             (maphash
                                              (lambda (k _) (push k acc))
                                              inputs)
                                             acc)
                                           #'string<))))
                    (when names
                      (let ((n (length names)))
                        (dotimes (i n)
                          (let* ((name (nth i names))
                                 (lastp (= i (1- n)))
                                 (branch (if lastp "└───" "├───"))
                                 (val (gethash name inputs)))
                            (if (vectorp val)
                                (push (concat prefix branch name
                                              " follows input '"
                                              (aref val 0) "'")
                                      lines)
                              (let* ((child (gethash val nodes))
                                     (child-prefix (concat prefix
                                                           (if lastp
                                                               "    "
                                                             "│   "))))
                                (push (concat prefix branch name
                                              (let ((src (nixos--flake-input-source child)))
                                                (if src (concat ": " src) "")))
                                      lines)
                                (unless (or (null val) (member val visited))
                                  (walk val child-prefix (cons val visited))))))))))))
      (walk root "" (list root)))
    (nreverse lines)))

(defun nixos--flake-metadata-fields (meta)
  "Return an alist of ((LABEL . VALUE) ...) from flake metadata META.

META is the hash table from `nix flake metadata --json', or nil.
Only human-meaningful fields are extracted: description, path, url,
revision, last-modified and inputs.  Sparse values are omitted.  The
\"Inputs:\" value is a list of tree display lines (see
`nixos--flake-input-tree')."
  (and (hash-table-p meta)
       (let ((desc (gethash "description" meta))
             (path (gethash "path" meta))
             (url (gethash "url" meta))
             (rev (gethash "revision" meta))
             (last (gethash "lastModified" meta))
             (inputs (and (hash-table-p (gethash "locks" meta))
                          (gethash "nodes" (gethash "locks" meta))))
             (root (and (hash-table-p (gethash "locks" meta))
                        (gethash "root" (gethash "locks" meta)))))
         (delq nil
               (list
                (when (and desc (not (string-empty-p desc)))
                  (cons "Description:" desc))
                (when (and path (not (string-empty-p path)))
                  (cons "Path:" path))
                (when (and url (not (string-empty-p url)))
                  (cons "URL:" url))
                (when (and rev (not (string-empty-p rev)))
                  (cons "Revision:" rev))
                (when (and last (not (eq last :null)))
                  (cons "Last modified:"
                        (format-time-string "%Y-%m-%d %H:%M"
                                            (seconds-to-time last))))
                (when (and (hash-table-p inputs) (stringp root))
                  (cons "Inputs:" (nixos--flake-input-tree inputs root))))))))

(defun nixos--abbreviate-path (path)
  "Abbreviate a filesystem PATH for display, or return it unchanged.
Only absolute local paths (starting with a slash or a tilde) are sent
through `abbreviate-file-name'; URLs and flake references such as
\"github:...\" are left untouched."
  (if (and (stringp path) (string-match-p "\\`[/~]" path))
      (abbreviate-file-name path)
    path))

(defun nixos--display-flake-overview (ref cache &optional meta)
  "Create a whole-flake detail buffer for REF from CACHE.

CACHE is the path-keyed leaf hash table from
`nixos--flake-flatten'.  META is optional data from
`nix flake metadata --json' shown as flake-level fields above the
output list.  Pressing RET (or clicking) on a line opens the
node's detail buffer via `nixos--display-flake'."
  (let* ((buf-name (format "*nixos-flake %s*"
                           (nixos--abbreviate-path ref)))
         (buf (get-buffer-create buf-name))
         (names (sort (hash-table-keys cache) #'string<)))
    (with-current-buffer buf
      (let ((inhibit-read-only t))
        (erase-buffer)
        (nixos-browse-mode)
        (use-local-map nixos-flake-overview-mode-map)
        ;; The overview buffer is not bookmarkable (node-only bookmarks),
        ;; and regenerating it re-runs `nix flake show' on the ref.
        (setq-local bookmark-make-record-function nil)
        (setq-local revert-buffer-function
                    (lambda (&rest _) (nixos-flake ref)))
        (nixos--browse-setup 'flake ref)
        (setq-local nixos--browse-flake-ref ref)
        (setq-local nixos--browse-name ref)
        ;; Fields are right-aligned to the longest label plus one column,
        ;; so every value starts on the same column (the same pattern used
        ;; for build-input alignment in `nixos--display-package').
        (let* ((fields (nixos--flake-metadata-fields meta))
               (label-width (apply #'max (mapcar #'string-width
                                                 (cons "Flake:" (mapcar #'car fields)))))
               ;; Pad LABEL to label-width, then one separating space.
               (pad (lambda (label)
                      (format (format "%%-%ds " label-width) label))))
          (insert (propertize (funcall pad "Flake:")
                              'face 'nixos-field-label)
                  (propertize (nixos--abbreviate-path ref)
                              'face 'nixos-package-name)
                  "\n")
          ;; Scalar metadata fields (Flake, Description, ...), each label and
          ;; value on one line, right-aligned to the longest label.  The
          ;; multi-line Inputs list is handled separately below.
          (dolist (field fields)
            (when (not (listp (cdr field)))
              (insert (propertize (funcall pad (car field))
                                  'face 'nixos-field-label)
                      (if (cdr field) (nixos--abbreviate-path (cdr field)) "")
                      "\n")))
          ;; Inputs tree, rendered like the Outputs section below: a header
          ;; line then the nested tree, separated by a blank line.  Each line
          ;; is already formatted with its tree prefix, so it is inserted
          ;; verbatim (no re-alignment or abbreviation).
          (let ((inputs (cdr (assoc "Inputs:" fields))))
            (when inputs
              (insert "\n" (propertize "Inputs:" 'face 'nixos-field-label) "\n")
              (dolist (item inputs)
                (insert item "\n"))))
          (insert "\n")
          ;; Node list header.
          (insert (propertize (format "Outputs (%d):" (length names))
                              'face 'nixos-field-label)
                  "\n")
          ;; Clickable lines.  The type and description columns align at the
          ;; longest node path plus one column.
          (let* ((max-path (if names
                               (apply #'max (mapcar #'string-width names))
                             0))
                 (max-type (apply #'max 0
                                  (mapcar (lambda (n)
                                            (let ((ty (gethash "type" (gethash n cache))))
                                              (if ty (string-width ty) 0)))
                                          names))))
            (dolist (name names)
              (let* ((data (gethash name cache))
                     (type (gethash "type" data))
                     (type-w (and type (string-width type)))
                     (desc (nixos--trim-description
                            (nixos--slurp-description data))))
                (insert-text-button name
                                    'action
                                    (lambda (_)
                                      (nixos--display-flake
                                       name (gethash name cache) ref))
                                    'follow-link t
                                    'face 'link
                                    'help-echo (format "View output: %s" name)
                                    'button-data name)
                (insert (make-string (+ 1 (- max-path (string-width name))) ?\s))
                (when type
                  (insert (propertize type 'face 'nixos-field-label))
                  (when desc
                    (insert (make-string (+ 1 (- max-type type-w)) ?\s))))
                (when desc
                  (insert (propertize desc 'face 'nixos-description)))
                (insert "\n")))))
        (goto-char (point-min))
        (set-buffer-modified-p nil)))
    (pop-to-buffer buf)))
;;;###autoload
(defun nixos-flake (&optional flake-ref)
  "Show the outputs of a Nix flake in a detail buffer.

Runs `nix flake show --json' on FLAKE-REF and presents a
whole-flake overview: the reference plus a clickable list of every
leaf node — derivations, apps, NixOS configurations, templates,
etc. — with its full dotted path.  Pressing \[nixos-flake-visit-output]
(or clicking) on a node opens that node's detail buffer.

Called interactively without a prefix, FLAKE-REF defaults to the
project root when it is a flake (contains flake.nix); otherwise it
is prompted for.  With \[universal-argument] it is always prompted
for, defaulting to the current directory.

When FLAKE-REF is non-nil it is used directly (as a programmatic
argument or from a bookmark)."
  (interactive "P")
  (let* ((ref (cond
               ((stringp flake-ref) flake-ref)
               (flake-ref (nixos--read-flake-ref))
               ((nixos--project-flake-ref))
               (t (nixos--read-flake-ref))))
         (ref (if (string-prefix-p "~" ref) (expand-file-name ref) ref)))
    (message "Showing flake %s..." ref)
    (let ((show (nixos--call-flake-show ref)))
      (cond
       ((and (consp show) (car show))
        (let* ((json (car show))
               (cache (nixos--flake-flatten json))
               (meta (car (nixos--call-flake-metadata ref))))
          (setq nixos--flake-cache cache
                nixos--flake-ref ref)
          (nixos--display-flake-overview ref cache meta)))
       ((consp show)
        (user-error "flake show failed:\n%s" (cdr show)))
       (t (user-error "`nix' executable not found (check `nix-executable')"))))))

(defun nixos--read-flake-ref ()
  "Prompt for a flake reference, defaulting to the current directory."
  (let ((r (read-string "nix flake show> " default-directory)))
    (if (string-prefix-p "~" r) (expand-file-name r) r)))

(defun nixos--project-flake-ref ()
  "Return the project root when it is a flake, else nil.

The root is the directory returned by `project-current' (via
`project-root'); it qualifies only when it contains a flake.nix."
  (let ((root (and (fboundp 'project-current)
                   (fboundp 'project-root)
                   (let ((pr (project-current t)))
                     (and pr (project-root pr))))))
    (when root
      (let ((flake-file (expand-file-name "flake.nix" root)))
        (when (file-exists-p flake-file)
          root)))))


;;; Bookmarks

(defconst nixos--package-expr-tail
  (concat
   "  depInfo = deps: map (d:"
   "    { name = d.pname or d.name or \"unknown\";"
   "      storePath = d.outPath;"
   "    }) deps;"
   " in [ pkg.meta pkg.outPath pkg.version"
   "     (depInfo (pkg.buildInputs or []))"
   "     (depInfo (pkg.nativeBuildInputs or []))"
   "     (pkg.pname or \"\")"
   "     (pkg.src.meta.homepage or pkg.src.url or \"\")"
   "     (pkg.meta.position or \"\") ]"))

(defun nixos--parse-package-result (result)
  "Parse the JSON RESULT vector from nix-instantiate into an alist.
RESULT is the parsed JSON vector:
  [meta outPath version buildInputs nativeBuildInputs pname repository]
Returns a cons cell (ALIST . \"\") on success, or (nil . ERROR-MSG)."
  (if (not (vectorp result))
      (cons nil (format "Unexpected JSON type (expected array): %S" result))
    (let ((meta (and (>= (length result) 1) (aref result 0)))
          (out (and (>= (length result) 2) (aref result 1)))
          (ver (and (>= (length result) 3) (aref result 2)))
          (build (and (>= (length result) 4) (aref result 3)))
          (native (and (>= (length result) 5) (aref result 4)))
          (pname (and (>= (length result) 6) (aref result 5)))
          (repo (and (>= (length result) 7) (aref result 6)))
          (pos (and (>= (length result) 8) (aref result 7))))
      (cons (list (cons 'meta (and meta (not (eq meta :null)) meta))
                  (cons 'outPath (and out (not (eq out :null)) out))
                  (cons 'version (and ver (not (eq ver :null)) ver))
                  (cons 'buildInputs (and build (vectorp build) (not (eq build :null)) build))
                  (cons 'nativeBuildInputs (and native (vectorp native) (not (eq native :null)) native))
                  (cons 'pname (and pname (not (eq pname :json-false)) pname))
                  (cons 'repository (and repo (not (eq repo :json-false)) (not (string-empty-p repo)) repo))
                  (cons 'position (and pos (not (eq pos :json-false)) (not (string-empty-p pos)) pos)))
            ""))))

(defun nixos--call-nix-package-expr (expr &rest extra-args)
  "Call nix-instantiate with EXPR and EXTRA-ARGS, return (RESULT . STDERR).
EXTRA-ARGS are passed directly to call-process before \"-E\".

Returns a cons cell (ALIST . STDERR): on success ALIST is the
parsed package alist and STDERR is an empty string.  On failure
ALIST is nil and STDERR contains the error output.  Returns nil
entirely if nix-instantiate is unavailable."
  (when (and (boundp 'nix-instantiate-executable)
             (stringp nix-instantiate-executable))
    (condition-case err
        (let* ((stderr-file (make-temp-file "nixos-stderr-"))
               (args (append (list nix-instantiate-executable nil (list t stderr-file) nil)
                             extra-args
                             (list "--strict" "--json" "--eval" "-E" expr))))
          (unwind-protect
              (with-temp-buffer
                (let ((exit-code (apply 'call-process args)))
                  (if (zerop exit-code)
                      (progn
                        (goto-char (point-min))
                        (nixos--parse-package-result (json-parse-buffer)))
                    (cons nil (with-temp-buffer
                                (insert-file-contents stderr-file)
                                (buffer-string))))))
            (delete-file stderr-file)))
      (file-missing (ignore err) nil))))

(defun nixos--call-nix-url-expr (url)
  "Call nix-instantiate with a tarball URL, return (RESULT . STDERR).
Downloads the tarball at URL via builtins.fetchTarball, imports
it with pkgs.callPackage, and extracts package metadata.

Uses --impure since the tarball is fetched without a pinned hash.
Returns the same format as `nixos--call-nix-package-expr'."
  (nixos--call-nix-package-expr
   (concat "{url}: let"
           "  pkgs = import <nixpkgs> {};"
           "  pkg = pkgs.callPackage"
           "    (builtins.fetchTarball url) {};"
           nixos--package-expr-tail)
   "--impure" "--argstr" "url" url))

(defun nixos--package-meta (package-name)
  "Fetch metadata, outPath, version and build deps for PACKAGE-NAME.
Returns an alist with keys `meta' (hash table), `outPath' (string),
`version' (string), `buildInputs' (vector of dep attrsets), and
`nativeBuildInputs' (vector of dep attrsets), or nil if
nix-instantiate is not available.

Results are memoized: since Nix store paths are immutable, the
metadata for a given package is stable forever."
  (unless nixos--package-meta-cache
    (setq nixos--package-meta-cache (make-hash-table :test 'equal)))
  (with-memoization (gethash package-name nixos--package-meta-cache)
    (car (nixos--call-nix-package-expr
          (concat "{cand}: let"
                  "  pkgs = import <nixpkgs> {};"
                  "  segments = builtins.filter builtins.isString"
                  "    (builtins.split \"\\\\.\" cand);"
                  "  pkg = builtins.foldl' (s: seg:"
                  "    builtins.getAttr seg s) pkgs segments;"
                  nixos--package-expr-tail)
          "--argstr" "cand" package-name))))


;;; Bookmarks

(defvar nixos--browse-name-list)
(defvar nixos--browse-name-prefix)

(defun nixos--browse-table-bookmark-make-record ()
  "Create a bookmark record for the current browse-table buffer.
Intended for use as `bookmark-make-record-function' in
`nixos-browse-options-mode' and `nixos-browse-packages-mode'."
  (let* ((type (cond ((derived-mode-p 'nixos-browse-options-mode) 'option)
                     ((derived-mode-p 'nixos-browse-packages-mode) 'package)
                     (t 'package)))
         (label (pcase type
                  ('option "option search")
                  ('package "package search")))
         (name-prefix nixos--browse-name-prefix))
    `(,(format "NixOS %s: %s" label (or name-prefix "all"))
      (type . ,type)
      (name-prefix . ,name-prefix)
      (handler . nixos--bookmark-jump))))

(defun nixos--bookmark-make-record ()
  "Create a bookmark record for the current browse buffer.
Intended for use as `bookmark-make-record-function'."
  (unless nixos--browse-name
    (user-error "No option or package to bookmark"))
  `(,(format "NixOS %s: %s"
             (pcase nixos--browse-type
               ('option "option")
               ('package "package")
               ('flake "flake"))
             nixos--browse-name)
    (type . ,nixos--browse-type)
    (name . ,nixos--browse-name)
    (handler . nixos--bookmark-jump)
    (source . ,nixos--browse-source)))

;;;###autoload
(defun nixos--bookmark-jump (bookmark)
  "Restore a nixos BOOKMARK.
Called by the bookmark system."
  (let ((type (alist-get 'type bookmark))
        (name (alist-get 'name bookmark))
        (name-prefix (alist-get 'name-prefix bookmark)))
    (if (assq 'name-prefix bookmark)
        ;; Table (search) bookmark — re-derive filtered name-list
        ;; from current cache, so new results appear on reopen.
        (cl-case type
          (option (nixos-browse-options
                   (and name-prefix (nixos--search-names 'option name-prefix))
                   name-prefix))
          (package (nixos-browse-packages
                    (and name-prefix (nixos--search-names 'package name-prefix))
                    name-prefix))
          (t (user-error "Unknown bookmark type %s" type)))
      ;; Detail bookmark.
      (cl-case type
        (option (nixos-option name))
        (package (pcase (alist-get 'source bookmark)
                   (`(url . ,url) (nixos-package-url url))
                   (`(local . ,dir)
                    (let ((default-directory dir))
                      (nixos-package-local)))
                   (_ (nixos-package name))))
        (flake (let ((ref (cdr (alist-get 'source bookmark))))
                 (let ((data (and nixos--flake-cache
                                  (gethash name nixos--flake-cache))))
                   (if data
                       (nixos--display-flake name data ref)
                     (let ((json (and ref (car (nixos--call-flake-show ref))))
                           cache)
                       (when (hash-table-p json)
                         (setq cache (nixos--flake-flatten json)))
                       (let ((data (and cache (gethash name cache))))
                         (if data
                             (nixos--display-flake name data ref)
                           (user-error "Flake node `%s' not found" name))))))))
        (t (user-error "Unknown bookmark type %s" type))))))


;;; Interactive commands

;;;###autoload
(defun nixos-option (&optional option-name)
  "Browse NixOS options, then display the selected one.
When called interactively, prompt with completion.  When
OPTION-NAME is provided non-interactively, display that option
directly."
  (interactive)
  (let ((cand (or option-name
                  (completing-read "nixos-option> "
                                   #'nixos--option-collection))))
    (let ((data (gethash cand (nixos--options-load))))
      (if data
          (nixos--display-option cand data)
        (user-error "Option `%s' not found" cand)))))

;;;###autoload
(defun nixos-package (&optional package-name)
  "Browse Nix packages, then display the selected one.
When called interactively, prompt with completion.  When
PACKAGE-NAME is provided non-interactively, display that package
directly.

Package metadata (including the store path for requisites view)
is obtained from `nix-instantiate' when available; otherwise the
contents of `nixos-search-json-file' are shown."
  (interactive)
  (let ((cand (or package-name
                  (completing-read "nix-pkg> "
                                   #'nixos--package-collection))))
    (let ((info (nixos--package-meta cand)))
      (if info
          (nixos--display-package cand info)
        ;; Fall back to the search JSON data.
        (let* ((full-key (concat nixos--package-key-prefix cand))
               (data (gethash full-key (nixos--packages-load))))
          (if data
              (nixos--display-package
               cand
               (list (cons 'meta data)))
            (user-error "Package `%s' not found" cand)))))))

;;;###autoload
(defun nixos-package-local ()
  "Display the Nix package defined by ./default.nix in `default-directory'.
Evaluates with `pkgs.callPackage ./default.nix {}'.

No memoization — intended for local development where
`default.nix' changes between invocations."
  (interactive)
  (let* ((full-dir (expand-file-name default-directory))
         (display-name (abbreviate-file-name full-dir))
         (default-directory full-dir))
    (unless (file-exists-p "default.nix")
      (user-error "No default.nix in %s" display-name))
    (message "Evaluating %sdefault.nix..." display-name)
    (pcase-let ((`(,info . ,stderr)
                 (nixos--call-nix-package-expr
                  (concat "let"
                          "  pkgs = import <nixpkgs> {};"
                          "  pkg = pkgs.callPackage ./default.nix {};"
                          nixos--package-expr-tail))))
      (if info
          (nixos--display-package (or (alist-get 'pname info) display-name)
                                  info (cons 'local full-dir))
        (user-error "%sdefault.nix:\n%s" display-name stderr)))))

;;;###autoload
(defun nixos-package-url (url)
  "Display the Nix package defined by a tarball at URL.
Downloads and evaluates the tarball via
`builtins.fetchTarball' + `pkgs.callPackage'.

Only point this at URLs you trust: evaluation uses --impure, so
the tarball's Nix code can read local files and environment
variables, and trigger import-from-derivation builds.

No memoization — intended for remote development where the
tarball may change between invocations."
  (interactive "sNix package URL: ")
  (let ((display-name (file-name-base (file-name-sans-extension (url-unhex-string url)))))
    (message "Evaluating %s..." url)
    (pcase-let ((`(,info . ,stderr)
                 (nixos--call-nix-url-expr url)))
      (if info
          (nixos--display-package (or (alist-get 'pname info) display-name)
                                  info (cons 'url url))
        (user-error "URL %s:\n%s" url stderr)))))


;;; Thing-At-Point

(defconst nixos--id-chars (string-to-list "-A-Za-z0-9_'\.")
  "Characters that can appear in a dotted NixOS identifier.
A list of chars with the hyphen first (so it is literal in both
`skip-chars-forward' and `rx' char sets).  Shared by
`nixos--dotted-identifier-re' and `nixos--option-bounds'.")

(defconst nixos--dotted-identifier-re
  (let ((any-chars (append '(any) nixos--id-chars)))
    (rx-to-string
     (list 'seq 'bos
           any-chars
           (list '* any-chars)
           "."
           (list '* any-chars)
           'eos)))
  "Regexp matching a dotted NixOS option or package identifier.
Must contain at least one dot and match Nix identifier rules.")

(defun nixos--option-at-point ()
  "Return the NixOS option reference around point, or nil.
Works in `nix-mode' buffers when point is on a dotted
identifier like \"services.postgresql.enable\"."
  (when (derived-mode-p 'nix-mode)
    (let ((bounds (nixos--option-bounds)))
      (when bounds
        (buffer-substring-no-properties (car bounds) (cdr bounds))))))

(defun nixos--option-bounds ()
  "Return the bounds of a NixOS option reference around point."
  (when (derived-mode-p 'nix-mode)
    (let* ((p (point))
           (id-chars (concat nixos--id-chars))
           start end)
      (save-excursion
        ;; Scan backward to the start.
        (skip-chars-backward id-chars)
        (setq start (point))
        ;; Scan forward to the end.
        (goto-char p)
        (skip-chars-forward id-chars)
        (setq end (point))
        (when (and (> end start)
                   (string-match-p nixos--dotted-identifier-re
                                   (buffer-substring-no-properties start end)))
          (cons start end))))))

(put 'nixos-option 'bounds-of-thing-at-point #'nixos--option-bounds)
(put 'nixos-option 'thing-at-point #'nixos--option-at-point)

;;;###autoload
(defun nixos-thing-at-point-setup ()
  "Enable `thingatpt' integration for `nixos-option' in the current buffer.
Add this to `nix-mode-hook' for automatic setup:

  (add-hook \\='nix-mode-hook #\\='nixos-thing-at-point-setup)"
  (interactive)
  (setq-local thing-at-point-provider-alist
              (cons '(nixos-option . nixos--option-at-point)
                    thing-at-point-provider-alist)))


(defvar-local nixos--browse-name-list nil
  "Buffer-local list of item names that the browse buffer is filtered to.
When nil, all items are shown.  Set by browse-table commands
and used by refresh to preserve the filter.")
(put 'nixos--browse-name-list 'permanent-local t)

(defvar-local nixos--browse-name-prefix nil
  "Buffer-local search term used for naming the browse buffer.
When non-nil, the buffer name includes this term (e.g.
\"*Nix Packages: htop*\").  Used by bookmarks to recreate
the buffer with the original name.")
(put 'nixos--browse-name-prefix 'permanent-local t)


;;; Tabulated Browse Mode (shared macro)

(cl-defmacro nixos--define-browse-mode (type &key mode-label buffer-name
                                             columns sort-key
                                             extract-fields
                                             visit-fn url-fmt cache-fn
                                             key-fn)
  "Define a tabulated-list browse mode for TYPE (a symbol, e.g. option).
Internal use only."
  (declare (indent 1))
  (let* ((typestr (symbol-name type))
         (mode (intern (format "nixos-browse-%ss-mode" typestr)))
         (mode-map (intern (format "nixos-browse-%ss-mode-map" typestr)))
         (visit (intern (format "nixos-browse-%ss-visit" typestr)))
         (search-url (intern (format "nixos-browse-%ss-search-url" typestr)))
         (refresh (intern (format "nixos-browse-%ss-refresh" typestr)))
         (cmd (intern (format "nixos-browse-%ss" typestr)))
         (entry-fn (intern (format "nixos-browse-%ss--entry" typestr)))
         (entries-fn (intern (format "nixos-browse-%ss--entries" typestr)))
         (current-name-fn (intern (format "nixos-browse-%ss--current-name" typestr))))
    `(progn
       (defvar-keymap ,mode-map
         :doc ,(format "Keymap for `%s'." mode)
         :parent tabulated-list-mode-map
         "RET" #',visit
         ,@(if url-fmt
               `("b"   #',search-url)
             nil))

       (define-derived-mode ,mode tabulated-list-mode
         ,mode-label
         ,(format "Major mode for browsing Nix %s in a sortable table.

\\{%s}" typestr mode-map)
         (setq tabulated-list-format ,columns)
         (setq tabulated-list-padding 2)
         (setq tabulated-list-sort-key ',sort-key)
         (tabulated-list-init-header)
         (hl-line-mode 1)
         (setq-local revert-buffer-function #',refresh)
         (setq-local bookmark-make-record-function
                     #'nixos--browse-table-bookmark-make-record))

       (defun ,entry-fn (name data)
         ,(format "Return a `tabulated-list' entry for %s NAME with DATA." typestr)
         (list name (vector (propertize name 'face 'nixos-package-name) ,@extract-fields)))

       (defun ,entries-fn (&optional name-list)
         ,(format "Generate `tabulated-list-entries' for %s.
When NAME-LIST is non-nil, only include entries whose names
appear in the list." typestr)
         (let ((items (,cache-fn))
               entries)
           (if (= (hash-table-count items) 0)
               (user-error "No %s loaded (check the JSON file)" ,typestr)
             (maphash
              (lambda (raw-key data)
                (let ((name ,(if key-fn `(funcall ,key-fn raw-key) 'raw-key)))
                  (when (or (null name-list) (member name name-list))
                    (push (,entry-fn name data) entries))))
              items)
             (nreverse entries))))

       (defun ,current-name-fn ()
         ,(format "Return the %s name at point, or signal an error." typestr)
         (or (tabulated-list-get-id)
             (user-error "No %s on this line" ,typestr)))

       (defun ,visit ()
         ,(format "Display details for the %s at point." typestr)
         (interactive)
         (,visit-fn (,current-name-fn)))

       ,(if url-fmt
            `(defun ,search-url ()
               ,(format "Open the current %s on search.nixos.org." typestr)
               (interactive)
               (browse-url (format ,url-fmt (,current-name-fn))))
          nil)

       (defun ,refresh (&rest _ignored)
         ,(format "Refresh the %s table.
Optional IGNORED args accommodate the `revert-buffer-function'
calling convention." typestr)
         (interactive)
         (setq tabulated-list-entries
               (,entries-fn nixos--browse-name-list))
         (tabulated-list-print t))

       ;;;###autoload
       (defun ,cmd (&optional name-list name-prefix)
         ,(format "Display Nix %s in a browseable table.

%s are shown with sortable columns.
\<%s>
\\[%s] on an entry to view full details,
\\[%s] to open on search.nixos.org,
\\[revert-buffer] to reload the data.

When NAME-LIST is non-nil (a list of names), only those entries
are displayed.  This is used by Embark export.

When NAME-PREFIX is non-nil, it is appended to the buffer name
(e.g. \"*NixOS Options: htop*\"), allowing multiple searches
to coexist in separate buffers.

Emacs' built-in narrowing (\\[narrow-to-defun] etc.) can be used
to filter the view in-place." typestr typestr mode-map visit search-url)
         (interactive)
         (let ((buf-name (if name-prefix
                             (concat (substring ,buffer-name 0 -1)
                                     ": " name-prefix "*")
                           ,buffer-name)))
           (let ((buf (get-buffer-create buf-name)))
             (with-current-buffer buf
               (,mode)
               (setq-local nixos--browse-name-list name-list)
               (setq-local nixos--browse-name-prefix name-prefix)
               (setq-local default-directory
                           (or (nixos--ensure-nixpkgs-root)
                               default-directory))
               (setq tabulated-list-entries
                     (,entries-fn name-list))
               (tabulated-list-print))
             (switch-to-buffer buf)))))))

;; Options table

(nixos--define-browse-mode option
  :mode-label "NixOS-Options"
  :buffer-name "*NixOS Options*"
  :columns [("Option" 50 t) ("Type" 20 t) ("Description" 0 nil)]
  :sort-key ("Option" . nil)
  :extract-fields ((or (gethash "type" data) "")
                   (propertize (or (nixos--trim-description
                                    (nixos--slurp-description data)) "")
                               'face 'nixos-description))
  :visit-fn nixos-option
  :url-fmt nixos-option-search-url-template
  :cache-fn nixos--options-load
  :key-fn nil)


;;; Eldoc

(defun nixos-eldoc-function (callback &rest _ignored)
  "Eldoc documentation function for NixOS options at point.
Calls CALLBACK with the option description when point is on a
NixOS option reference in `nix-mode'.  Only returns docs when the
options cache is already populated (does not trigger a load)."
  (when (and (derived-mode-p 'nix-mode)
             nixos--options-cache)
    (when-let* ((opt (nixos--option-at-point))
                (data (gethash opt nixos--options-cache))
                (desc (nixos--slurp-description data)))
      (funcall callback desc))))

;;;###autoload
(defun nixos-eldoc-setup ()
  "Enable eldoc support for NixOS options in the current buffer.
Add this alongside `nixos-thing-at-point-setup' in
`nix-mode-hook' for full integration:

  (add-hook \='nix-mode-hook #\='nixos-thing-at-point-setup)
  (add-hook \='nix-mode-hook #\='nixos-eldoc-setup)"
  (add-hook 'eldoc-documentation-functions
            #'nixos-eldoc-function nil t))


;;; Package Browse Mode

(nixos--define-browse-mode package
  :mode-label "NixOS-Packages"
  :buffer-name "*Nix Packages*"
  :columns [("Package" 40 t) ("Version" 15 t) ("Description" 0 nil)]
  :sort-key ("Package" . nil)
  :extract-fields ((propertize (or (gethash "version" data) "")
                               'face 'nixos-version)
                   (propertize (or (nixos--trim-description
                                    (nixos--slurp-description data)) "")
                               'face 'nixos-description))
  :visit-fn nixos-package
  :url-fmt nixos-package-search-url-template
  :cache-fn nixos--packages-load
  :key-fn (lambda (k) (string-remove-prefix nixos--package-key-prefix k)))


;; The browse-table commands are defined inside the macro above; the
;; ;;;###autoload cookie sits indented in the macro body so the
;; loaddefs scraper never sees it.  Emit explicit autoloads so the
;; commands are available before the package loads.
(autoload 'nixos-browse-options "nixos" nil t)
(autoload 'nixos-browse-packages "nixos" nil t)


;;; Embark

;; Value-less defvars: silence the byte-compiler without binding the
;; variables, so embark's own `defcustom' defaults survive when
;; nixos.el loads first.
(defvar embark-exporters-alist)
(defvar embark-keymap-alist)
(defvar embark-general-map)

(defun nixos--embark-export-option (candidates)
  "Embark export function for NixOS option CANDIDATES."
  (nixos-browse-options candidates))

(defun nixos--embark-export-package (candidates)
  "Embark export function for Nix package CANDIDATES."
  (nixos-browse-packages candidates))

(defun nixos--embark-browse-option-url (cand)
  "Open CAND on search.nixos.org options."
  (browse-url (format nixos-option-search-url-template cand)))

(defun nixos--embark-browse-package-url (cand)
  "Open CAND on search.nixos.org packages."
  (browse-url (format nixos-package-search-url-template cand)))

(defvar-keymap nixos-embark-option-map
  :doc "Embark actions for NixOS option candidates.
The parent is set to `embark-general-map' once Embark loads."
  "RET" #'nixos-option
  "b"   #'nixos--embark-browse-option-url
  "i"   #'insert)

(defvar-keymap nixos-embark-package-map
  :doc "Embark actions for Nix package candidates.
The parent is set to `embark-general-map' once Embark loads."
  "RET" #'nixos-package
  "b"   #'nixos--embark-browse-package-url
  "i"   #'insert)

(with-eval-after-load 'embark
  ;; `defvar-keymap :parent' is evaluated once, at definition time,
  ;; when `embark-general-map' may not exist yet — wire it up here.
  (set-keymap-parent nixos-embark-option-map embark-general-map)
  (set-keymap-parent nixos-embark-package-map embark-general-map)
  (add-to-list 'embark-exporters-alist
               '(nixos-option . nixos--embark-export-option))
  (add-to-list 'embark-exporters-alist
               '(nixos-package . nixos--embark-export-package))
  (add-to-list 'embark-keymap-alist
               '(nixos-option . nixos-embark-option-map))
  (add-to-list 'embark-keymap-alist
               '(nixos-package . nixos-embark-package-map)))

(provide 'nixos)
;;; nixos.el ends here
