;;; nixos.el --- Browse NixOS options and packages -*- lexical-binding: t -*-

;; Copyright (C) 2025-2026  Daniel Nagy

;; This file is free software: you can redistribute it and/or modify
;; it under the terms of the GNU Affero General Public License as
;; published by the Free Software Foundation, either version 3 of the
;; License, or (at your option) any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU Affero General Public License for more details.

;; You should have received a copy of the GNU Affero General Public
;; License along with this file.  If not, see
;; <https://www.gnu.org/licenses/>.

;; Author: Daniel Nagy
;; Version: 0.1.0
;; Keywords: tools, unix
;; Package-Requires: ((emacs "30.1") (nix-mode "0"))

;;; Commentary:

;; This package provides interactive `completing-read' interfaces for
;; browsing NixOS options and Nix packages.
;;
;; Data sources are configurable via `defcustom':
;;
;;   - `nixos-options-json-file'  -- NixOS option descriptions
;;     (generated by the NixOS manual; see default.nix for an example
;;     of how to expose it via `environment.etc').
;;
;;   - `nixos-search-json-file'   -- output of `nix search --json'
;;     (also demonstrated in default.nix).
;;
;; Commands:
;;
;;   M-x nixos-option   -- browse NixOS options
;;   M-x nixos-package  -- browse Nix packages
;;
;; Both commands use the standard completion framework, so they work
;; with icomplete, vertico, fido-mode, etc.  Annotation support is
;; provided out of the box (marginalia is fine too).

;;; Code:

(require 'json)

;; Forward-declare; nix-mode is optional at compile time.
(defvar nix-instantiate-executable)

(defgroup nixos nil
  "Browse NixOS options and packages."
  :group 'tools
  :prefix "nixos-")

(defcustom nixos-options-json-file "/etc/nixos-options.json"
  "Path to the NixOS options JSON file.

This file should contain a flat JSON object where each key is a
dotted option path (e.g. \"services.postgresql.enable\") and each
value is an object with at least a \"description\" field.

It can be generated from the NixOS manual and exposed via
`environment.etc' in your NixOS configuration."
  :type 'file
  :group 'nixos)

(defcustom nixos-search-json-file "/etc/nix-search.json"
  "Path to the Nix package search JSON file.

This file should contain the output of `nix search --json'.
Keys typically look like \"legacyPackages.x86_64-linux.htop\".

See default.nix for an example of how to generate and expose this
file in your NixOS configuration."
  :type 'file
  :group 'nixos)

(defcustom nixos-annotation-width 70
  "Maximum width of the description annotation shown during completion."
  :type 'integer
  :group 'nixos)


;;; Cache

(defvar nixos--options-cache nil
  "Cached hash table of NixOS options.
Keys are dotted option paths; values are alists with keys like
description, type, default, etc.")

(defvar nixos--packages-cache nil
  "Cached hash table of Nix packages.
Keys are full attribute paths (e.g.
\"legacyPackages.x86_64-linux.htop\"); values are alists with
keys like pname, version, description, etc.")

(defvar nixos--packages-keys nil
  "Cached list of short package names (prefix stripped).")

(defun nixos--options-load ()
  "Load NixOS options from `nixos-options-json-file' into cache.
Returns the cached hash table."
  (unless nixos--options-cache
    (if (file-readable-p nixos-options-json-file)
        (setq nixos--options-cache
              (json-parse-file nixos-options-json-file))
      (setq nixos--options-cache (make-hash-table :test 'equal))))
  nixos--options-cache)

(defun nixos--packages-load ()
  "Load Nix packages from `nixos-search-json-file' into cache.
Returns the cached hash table."
  (unless nixos--packages-cache
    (let ((table (if (file-readable-p nixos-search-json-file)
                     (json-parse-file nixos-search-json-file)
                   (make-hash-table :test 'equal))))
      (setq nixos--packages-cache table
            nixos--packages-keys
            (sort (mapcar (lambda (k)
                            (string-remove-prefix
                             "legacyPackages.x86_64-linux." k))
                          (hash-table-keys table))
                  #'string<))))
  nixos--packages-cache)

(defun nixos-refresh-cache ()
  "Discard cached option and package data.
The next `nixos-option' or `nixos-package' invocation will reload
from the JSON files."
  (interactive)
  (setq nixos--options-cache nil
        nixos--packages-cache nil
        nixos--packages-keys nil)
  (message "nixos: cache cleared"))


;;; Helpers

(defun nixos--hash-ref (table &rest keys)
  "Look up KEYS recursively in TABLE.
Each key in KEYS is used with `gethash' to descend one level."
  (let ((cursor table))
    (while (and cursor keys)
      (setq cursor (gethash (car keys) cursor)
            keys (cdr keys)))
    cursor))

(defun nixos--slurp-description (inner)
  "Extract a one-line description string from INNER (a hash table or alist)."
  (let ((desc (cond
               ((hash-table-p inner) (gethash "description" inner))
               ((consp inner) (alist-get 'description inner nil nil #'equal))
               (t nil)))
        (pname (cond
                ((hash-table-p inner) (gethash "pname" inner))
                ((consp inner) (alist-get 'pname inner nil nil #'equal))
                (t nil))))
    (or desc pname "")))

(defun nixos--annotate (description)
  "Return a right-aligned annotation string for DESCRIPTION."
  (when (and description (not (string-empty-p description)))
    (concat (propertize " " 'display '(space :align-to center))
            (string-limit (string-replace "\n" " " description)
                          nixos-annotation-width))))


;;; Options

(defun nixos--option-annotate (candidate)
  "Completion annotation function for NixOS option CANDIDATE."
  (nixos--annotate
   (nixos--slurp-description
    (gethash candidate (nixos--options-load)))))

(defun nixos--option-collection (string predicate action)
  "Completion collection for NixOS options.
See `completing-read' for the meaning of STRING, PREDICATE and
ACTION."
  (pcase action
    ('metadata
     '(metadata
       (annotation-function . nixos--option-annotate)))
    (_
     (complete-with-action action
                           (hash-table-keys (nixos--options-load))
                           string predicate))))


;;; Packages

(defun nixos--package-annotate (candidate)
  "Completion annotation function for Nix package CANDIDATE."
  (let ((full-key (concat "legacyPackages.x86_64-linux." candidate)))
    (nixos--annotate
     (nixos--slurp-description
      (gethash full-key (nixos--packages-load))))))

(defun nixos--package-collection (string predicate action)
  "Completion collection for Nix packages.
See `completing-read' for the meaning of STRING, PREDICATE and
ACTION."
  (pcase action
    ('metadata
     '(metadata
       (annotation-function . nixos--package-annotate)))
    (_
     (nixos--packages-load)              ; ensure nixos--packages-keys exists
     (complete-with-action action
                           nixos--packages-keys
                           string predicate))))


;;; Display

(defun nixos--display (title raw-json &optional json-mode-p)
  "Display RAW-JSON in a read-only buffer titled TITLE.
When JSON-MODE-P is non-nil, enable `json-mode' in the buffer."
  (let ((buf (generate-new-buffer title)))
    (with-current-buffer buf
      (insert raw-json)
      (let ((inhibit-read-only t))
        (goto-char (point-min))
        (when (looking-at-p "{")
          (json-pretty-print-buffer)))
      (when (and json-mode-p (fboundp 'json-mode))
        (json-mode))
      (goto-char (point-min))
      (read-only-mode 1)
      (set-buffer-modified-p nil))
    (switch-to-buffer buf)))

(defun nixos--package-meta (package-name)
  "Fetch metadata for PACKAGE-NAME using `nix-instantiate'.
Returns a JSON string, or nil if nix-instantiate is not
available."
  (when (and (boundp 'nix-instantiate-executable)
             (stringp nix-instantiate-executable))
    (with-temp-buffer
      (when (zerop
             (call-process nix-instantiate-executable nil t nil
                           "--strict" "--json" "--eval"
                           "--argstr" "cand" package-name
                           "-E"
                           "{cand}: (import <nixpkgs> {}).${cand}.meta"))
        (buffer-string)))))


;;; Interactive commands

;;;###autoload
(defun nixos-option (&optional option-name)
  "Browse NixOS options, then display the selected one.
When called interactively, prompt with completion.  When
OPTION-NAME is provided non-interactively, display that option
directly."
  (interactive)
  (let ((cand (or option-name
                  (completing-read "nixos-option> "
                                   #'nixos--option-collection))))
    (let ((data (gethash cand (nixos--options-load))))
      (if data
          (nixos--display (format "*nixos-option %s*" cand)
                          (json-serialize data)
                          t)
        (user-error "Option `%s' not found" cand)))))

;;;###autoload
(defun nixos-package (&optional package-name)
  "Browse Nix packages, then display the selected one.
When called interactively, prompt with completion.  When
PACKAGE-NAME is provided non-interactively, display that package
directly.

Package metadata is obtained from `nix-instantiate' when
available; otherwise the contents of `nixos-search-json-file' are
shown."
  (interactive)
  (let ((cand (or package-name
                  (completing-read
                   ;; Avoid "package" in the prompt because
                   ;; Marginalia may interpret it specially.
                   "nix-pkg> "
                   #'nixos--package-collection))))
    (let ((meta-json (nixos--package-meta cand)))
      (if meta-json
          (nixos--display (format "*nixos-package %s*" cand)
                          meta-json
                          t)
        ;; Fall back to the search JSON data.
        (let* ((full-key (concat "legacyPackages.x86_64-linux." cand))
               (data (gethash full-key (nixos--packages-load))))
          (if data
              (nixos--display (format "*nixos-package %s*" cand)
                              (json-serialize data)
                              t)
            (user-error "Package `%s' not found" cand)))))))


(provide 'nixos)
;;; nixos.el ends here
